### ISSUE TITLE
Ren'py Android Porting no longer working because of Bintray being Down

### ISSUE THREAD

**Issue by Billarin** [renpy/renpy#2792] opened 2021-05-04 08:18 UTC
I've been having issues with android porting upon redownloading rapt and it seems several people also came across the same problem in lemmasoft. 
From the information i gained based on a kind person in reddit, this is due to bintray which provide the necessary .pom no longer working/up. 
[Reddit Conversation + error code](https://www.reddit.com/r/RenPy/comments/n3vgxy/android_build_keep_failing_with_this_error/)

I hope you can fix this as soon as possible :)

**Comment by mavyxdawn** [comment] 2021-05-04 12:45
Hi! I'm ZeilleDawn from the thread. I also encountered the same issue when I built on Android using Ren'Py Launcher 7.3.5.606. I attached the log here.
[android-7.3.5.txt](https://github.com/renpy/renpy/files/6421118/android-7.3.5.txt)

(I have 2 separate Ren'Py Launcher and my 7.4.4.1439 still works even after installing 7.3.5.606)

**Comment by Billarin** [comment] 2021-05-04 13:54
> Hi! I'm ZeilleDawn from the Reddit thread.
> 
> I installed Ren'Py Launcher 7.3.5.606 to help, but I also encountered the same issue when I built it on Android.
> 
> Android log can be found here:
> [android-7.3.5.txt](https://github.com/renpy/renpy/files/6421118/android-7.3.5.txt)
> 
> * What went wrong:
>   Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> 
> > Could not resolve com.danikula.expansion:expansion:1.3.4.
> > Required by:
> > project :app > project :renpyandroid
> > Could not resolve com.danikula.expansion:expansion:1.3.4.
> > > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/expansion/1.3.4/expansion-1.3.4.pom'.
> > > Could not HEAD 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/expansion/1.3.4/expansion-1.3.4.pom'. Received status code 403 from server: Forbidden
> > Could not resolve com.danikula.expansion:license:1.7.0.
> > Required by:
> > project :app > project :renpyandroid
> > Could not resolve com.danikula.expansion:license:1.7.0.
> > > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/license/1.7.0/license-1.7.0.pom'.
> > > Could not HEAD 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/license/1.7.0/license-1.7.0.pom'. Received status code 403 from server: Forbidden
> > Could not resolve com.danikula.expansion:zip:1.2.1.
> > Required by:
> > project :app > project :renpyandroid
> > Could not resolve com.danikula.expansion:zip:1.2.1.
> > > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/zip/1.2.1/zip-1.2.1.pom'.
> > > Could not HEAD 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/zip/1.2.1/zip-1.2.1.pom'. Received status code 403 from server: Forbidden
> 
> Additional info: I have 2 separate Ren'Py Launcher. My 7.4.4.1439 still works even after installing 7.3.5.606.
> So I tried installing another Ren'Py Launcher version to test. I installed 7.4.3.1414, and I'm not encountering the said issue.
> Here's the android log for 7.4.3.1414.
> [android-7.4.3.txt](https://github.com/renpy/renpy/files/6421214/android-7.4.3.txt)

Ah i tried it after seeing your comment but nonetheless same error for 7.4.4 , 7.3.5 , and 7.4.3 :(

**Comment by DipeshAggarwal** [comment] 2021-05-04 15:10
It seems like the platform, Bintray, is shutting down it's services so they have probably taken the files down. The gradle files need to be updated with new links

**Comment by renpytom** [comment] 2021-05-05 04:22
This is fixed by renpy/renpy-build#2d47f44

**Comment by Billarin** [comment] 2021-05-05 06:20
> This is fixed by [renpy/renpy-build@2d47f44](https://github.com/renpy/renpy-build/commit/2d47f44).

Hi @renpytom , thank you soo much for the quickfix!
Any chance you will be able to explain on how to use it?

**Comment by renpytom** [comment] 2021-05-05 06:22
Um... wait for the next nightly, and it should just work?

**Comment by mavyxdawn** [comment] 2021-05-05 06:24
Oh. So in Ren'Py Launcher > Update(lower right) > Nightly. Then it'll download the update. 
Just commented here in case it wasn't clear.

**Comment by Billarin** [comment] 2021-05-05 06:43
Okay thanks both ^^

**Comment by renpytom** [comment] 2021-05-05 06:43
Yes, but it won't be out until tomorrow morning's build. (Assuming it works.)

**Comment by Andykl** [comment] 2021-05-05 23:28
Not sure it caused by this, after clean apply of last nigtly, the build fails with [android.txt](https://github.com/renpy/renpy/files/6430799/android.txt)

**Comment by Billarin** [comment] 2021-05-06 15:48
> Not sure it caused by this, after clean apply of last nigtly, the build fails with [android.txt](https://github.com/renpy/renpy/files/6430799/android.txt)

Indeed i seems to be having similar problem, i guess we should just wait for the normal build instead of the nightly one and wait for the fix from renpytom

**Comment by renpytom** [comment] 2021-05-11 01:50
This should be fixed in the 7.4.5 prerelease.

**Closed by renpytom** 2021-05-11 01:50 UTC

**Comment by Phalzyr** [comment] 2021-06-07 14:53
> This should be fixed in the 7.4.5 prerelease.

was the ip changed to look for it or was the check removed completely? I ask as currently 7.3.5 is still used for android builds as some devs use it for the persistent save code. if it is just checking  different IP address then that be an easy work around...
