### ISSUE TITLE
Question: When bump python version to 3.11 or higher

### ISSUE THREAD

**Issue by Longtianmu** [renpy/renpy#4521] opened 2023-04-07 13:26 UTC
3.11 above includes some exciting function like module tomllib.
So I wonder if there is any plan to update python.

**Comment by renpytom** [comment] 2023-04-07 13:55
Fundamentally, yes. 

Moving to Python 3.11 will mean dropping support for Window 7, so I'm keeping an eye on statistics for Windows 7 usage to help inform when we switch.

**Closed** 2023-04-07 13:55 UTC
Labels: question

**Comment by Senyu** [comment] 2023-04-11 01:04
![wefwf](https://user-images.githubusercontent.com/75548744/231028654-1166cf58-bc3e-427c-a3f4-93cb22a49497.png)

Actually Python 3.9 to 3.11 can be run without problems on windows 7, as long as have "api-ms-win-core-path-l1-1-0.dll":
https://github.com/nalexandru/api-ms-win-core-path-HACK

The problem is that the python developers, added a lock on the Python 3.9 to 3.11 installer so it won't install on windows 7 and don't want to add the api-ms-win-core-path-l1-1-0-0.dll and don't want to support Win7 it anymore... Even if Python 3.9 or above is still supported.

Same thing with OBS Studio 29 in which you just have to add some missing code (I will not say here) in the *.dll to run on Win7.

Some software/game developers have been blocking the executable (.exe) or the code script, from running on win7 which is sad, then this forced blocking has to be removed to get it working again on Win7.

It's strange this crazy logic that the devs have been following based on microsoft... What I mean is that as long as DirectX 11/OpenGL is still used for many programs and games the win7 support will not really end... even more after microsoft did this:
https://github.com/microsoft/DirectX-Specs/blob/master/d3d/D3D12onWin7.md

Of course I am not saying that Renpytom has to continue Win7 support, but it is undeniable from what I have seen on internet forums that some people will modify the X program/game and return Win7 support.

And we already lost WinXP on Ren'Py, it would be sad to lose Win7 support for something forced and it is still compatible with newer versions of Python.
