### ISSUE TITLE
[7.4.9.2130] Cannot start any project in Android Emulator

### ISSUE THREAD

**Issue by O-Rud** [renpy/renpy#3074] opened 2021-10-04 13:39 UTC
Every time I try to start any project (including "Tutorial" and "The Question" delivered with renpy) in Android emulator I receive the following exception

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
TypeError: Cannot convert Null to renpy.display.render.Render

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 652, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3834, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "renpy/display/core.py", line 2559, in draw_screen
    renpy.display.draw.draw_screen(surftree)
  File "gl2draw.pyx", line 814, in renpy.gl2.gl2draw.GL2Draw.draw_screen
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 862, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
TypeError: Cannot convert Null to renpy.display.render.Render

Windows-10-10.0.19041
Ren'Py 7.4.9.2130
Ren'Py Launcher 7.4.9.2130
Mon Oct  4 14:40:54 2021


```

**Comment by renpytom** [comment] 2021-10-04 14:48
This is a duplicate of #3070 . (Doesn't look it, so thanks for reporting it, but it's the same issue.)

**Closed** 2021-10-04 14:51 UTC
