### ISSUE TITLE
Sentence stuck at {w=0.5} or {p=0.5}

### ISSUE THREAD

**Issue by yyou22** [renpy/renpy#3256] opened 2022-01-26 18:41 UTC
Hi, I notice that when I have a dialogue with {w=} or {p=} tag inserted with a wait time specified, occassionally the dialogue would get stuck at the tag without proceeding. 

For example, if I have

char "Hi, {w=0.5}nice to see you."

There is a slight chance that the dialogue would pause after "Hi," without ever proceeding. If I click again, it would fix itself and resume showing the rest of the sentence. In most cases, this seems harmless since the player can just click again and the issue will resolve itself, however in my case I have looping beeping sound attached to the character dialogues and the beeping sound would keep looping forever when instances like this happen. I tried to look into this myself and notice a few things:

1. This is more likely to happen if a variable's value gets changed right before the dialogue. For example:
$ var_name = "new_var_name"
char "Hi, {w=0.5}nice to see you."
However, there are also cases that it just happens out of nowhere.

2. I printed out the values of the callback event and it seems that when this happens, the callback event is stuck at "show_done" when it's supposed to be updated to "slow_done" since it is the end of a segment of the sentence.

3. It happens very often in one of my games, but never happens in my other game. I am not exactly sure why this is the case.

Thank you in advance for looking into this issue.

**Comment by renpytom** [comment] 2022-01-26 18:43
Does it happen without the looping beeping sound? And are you playing that sound effect on the voice channel?

**Comment by yyyyyyou** [comment] 2022-01-26 18:49
Hi renpytom, thank you for your prompt response. 

1. I am not sure if it happens without the looping beeping sound. I will test around and get back to you to see if I encounter the same problem without the beeping sound.
2. Yes, I am playing the sound effect on the voice channel. However, I registered a specific custom voice channel just for the beeping sound. Here's what my code roughly looks like:

init -1 python:
    renpy.music.register_channel("beep", "voice", True)

def clack_play(on=False):
        if on:
            renpy.music.set_volume(0.8, delay=0, channel='beep')
            renpy.music.play("music/beep.ogg", channel="beep", loop=True)
        else:
            renpy.music.stop(channel="beep", fadeout = 0.5)

    def beep(event, **kwargs):
        if event == "show" or event == "begin":
            clack_play(True)
        if event == "slow_done":
            clack_play(False)

Let me know if you need any further information.

**Comment by yyyyyyou** [comment] 2022-01-26 19:06
Hi renpytom,

I removed the beeping sound by setting callback to None in the character definition, and I was not able to recreate the same problem despite many playthroughs. So no, it seems that the issue does not occur without the beeping sound. Hope this helps.

**Comment by renpytom** [comment] 2022-01-26 19:09
Can you try, to see if it helps, 

```
init -1 python:
    renpy.music.register_channel("beep", "sfx", True)

    def clack_play(on=False):
        if on:
            renpy.music.set_volume(0.8, delay=0, channel='beep')
            renpy.music.play("music/beep.ogg", channel="beep", loop=True)
        else:
            renpy.music.stop(channel="beep", fadeout = 0.5)

    def beep(event, **kwargs):
        if event == "show" or event == "begin":
            clack_play(True)
        if event == "slow_done":
            clack_play(False)
```

Just to see if it's the vice mixer that's interfering.

**Comment by yyyyyyou** [comment] 2022-01-26 19:12
Hi renpytom, unfortunately the issue still occurs despite switching to the sfx channel.

**Comment by renpytom** [comment] 2022-01-26 19:12
Okay, I'll look into this when I get a chance.

**Comment by yyyyyyou** [comment] 2022-01-27 10:04
Hi renpytom, just to offer some updates, I think I was able to narrow down where the problem originates from:

1. I tried removing the beeping functionality in a different way by simply commenting out the line `renpy.music.play("music/beep.ogg", channel="beep", loop=True)` inside `clack_play()` instead of setting callback to None in the character definition. In other words, I left the callback function there, just without playing the beeping audio. However, the issue still occurs, leading me to believe that this is not a mixer or audio issue but rather how the callback function is handled.

2. I further looked into how the callback event is updated in `character.py`, and noticed that when this issue occurs, the `SlowDone()` class is never called despite the fact that it should, since it is at the end of a sentence segment. Therefore, the beeping continues because the callback event was never updated to "slow_done", and therefore the line
`clack_play(False)` was never called since it is wrapped in the if statement .

3. Another observation I had was that the issue occurs more frequently on sentences that have a shorter segement with fewer number of characters. In other words, it happens way more frequently on sentences that are like `char "Hello, {w=0.5} how are you?"` than `char "It has been a while, {w=0.5} how are you doing?"` since "Hello" is way shorter than "It has been a while." (And as a result, this happens way more often in Asian languages since they tend to have fewer characters in each sentence.) This behavior is also extremely inconsistent, meaning that during each playthrough the issue happens to different sentences. This led me to believe that this may be some sort of "timer issue."

4. And in the end, I was able to locate where the problem is happening, and it is at line 2001 in `text.py`:
```
if layout.redraw_typewriter(st) is None:
    if self.slow:
        self.call_slow_done(st)
        self.slow = False
```
The issue is that when this problem occurs, the value returned by `layout.redraw_typewriter(st)` is for some reason 0 rather than None, and therefore `self.call_slow_done(st)` is never called. And the way I understand it, it should always return None when the dialogue reaches the end of each sentence segement. Nonetheless, I am not familar with how renpy works behind the scenes so this is out of scope for me to understand what `redraw_typewriter(self, st)` does, but I hope this can offer you some useful insights.

**Comment by renpytom** [comment] 2022-01-28 00:46
Can you put together a small demo for me, please? Just so I have your code, and can easily run it to track this one down.

**Comment by yyyyyyou** [comment] 2022-01-28 03:43
Yes, for sure. Would emailing be fine? I'll get back to you when I have it ready.

**Comment by yyyyyyou** [comment] 2022-01-28 17:45
Hi renpytom, I have sent you an email with a small demo and some additional information that I think may be useful to you. Thank you again for looking into this issue and please let me know if you need any further information from me.

**Comment by renpytom** [comment] 2022-02-01 03:32
I've been  unable to repeat this here, after maybe 50 tries using the game you sent. I did add some more defensive programming to see if I can prevent this from happening. Could you try applying those patches, and seeing if they resolve the problem?

**Comment by yyyyyyou** [comment] 2022-02-01 15:18
Unfortunately I am still encountering the issue on my end with nightly build [7-nightly-2022-02-01-2c4b9affb](https://nightly.renpy.org/7-nightly-2022-02-01-2c4b9affb/index.html).

I am unsure if certain os or hardwares are more prone to the problem, however I know it is not unique since several players have also reached out to me about it and I have experienced it on different devices myself. Did you try reproducing the problem on the sentence "人的性格，{w=0.5}从经历而来。"? I find this sentence especially susceptible to the issue.

**Comment by yyyyyyou** [comment] 2022-02-01 18:34
Hi Tom, I think I was finally able to track down what's specifically exacerbating the problem in the prologue.

It turns out to be the real world digital clock being displayed in the bottom left of the screen, defined in `00_a_clock.rpy`. The original code was taken from [Lemma Soft Forums](https://lemmasoft.renai.us/forums/viewtopic.php?t=21978), and the `render(self, width, height, st, at)` function is updating the clock by constantly calling `renpy.redraw(self, 0)`. 

Do take my following statements as a grain of salt because admittingly I know nothing about how renpy renders displayables and could be very wrong, but my wild guess is that the non-stop constant calling of `renpy.redraw()` is interfering with `redraw_typewriter()` in `text.py` (perhaps the issue occurs when those two functions are called at the exact same instance?). After I cleaned up the code in `00_a_clock.rpy` and updated `renpy.redraw(self, 0)` to `renpy.redraw(self, 1)` (aka have the clock be redrawn every second instead of non-stop), the issue seems to be alleviated.

However, I have encountered the problem in other parts of the game without the digital clock (but with much less frequency), so I still need to investigate what may be the causes there, but I wonder it may be also related to the redrawing of displayables interfering with each other.

**Comment by renpytom** [comment] 2022-02-02 00:40
I'm still not able to repeat this, despite another 25 or so attempts, using the line you gave, just rolling back, then clicking. 

Can you try  d5a7a7c1 and see if that's helpful in the renpy.redraw(self, 0) case? In general, you don't want ``renpy.redraw(self, 0)`` if you can avoid it, so your fix is a good one. But this might improve this in other cases.

**Comment by yyyyyyou** [comment] 2022-02-02 23:59
Unfortunately the newest patch does not resolve the problem on my end (if left as `renpy.redraw(self, 0)`).

**Closed** 2022-05-11 04:37 UTC
