### ISSUE TITLE
Keyboard/Controller rebinding 

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5641] opened 2024-07-19 17:43 UTC
Key/controller rebinding is a must have in today's time. I've seen negative reviews pop up in many games only for not having rebinding. Players expect them as it were a basic feature of any game. It will be awesome for rebinding out of the box because the vast mayority of renpy games ship with the default renpy functionality.

I get that in visual novels this feature is not as important as in games with complex mechanics, but it will be a win for accessibility.

Steam review example:

![image-2](https://github.com/user-attachments/assets/286150c1-bbcb-4601-839f-bcee238cb9f0)

**Comment by renpytom** [comment] 2024-07-20 00:42
Duplicate of  #3429.

**Closed by renpytom** 2024-07-20 00:42 UTC
