### ISSUE TITLE
Launcher crashes on reboot

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2816] opened 2021-05-19 11:37 UTC
Happened when switching themes in the launcher, and also sometimes when enabling autoreload. Very hard to reproduce,
```
Full traceback:
  File "renpy/common/00start.rpy", line 213, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 498, in script
    python hide:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 498, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 508, in _execute_python_hide
    renpy.load("_reload-2")
  File "renpy/loadsave.py", line 768, in load
    roots, log = loads(location.load(filename))
  File "renpy/loadsave.py", line 63, in loads
    return cPickle.loads(s)
TypeError: __new__() takes at least 2 arguments (1 given)
```
Also disabling launcher reloading during an update could be good, as it can break ren'py.

**Comment by renpytom** [comment] 2021-05-21 23:15
If yo have the _reload-2-LT-1.save files from a crash, please send it to me. I'll disable it in the updater.

**Comment by Gouvernathor** [comment] 2021-05-22 00:10
I found [this](https://s3.seedboxws.com/ddl/usr00218/_reload-2-LT1.save) in my `AppData/Roaming/RenPy/launcher-4`, the date matches a few minutes before my OP.

**Comment by renpytom** [comment] 2021-05-22 00:38
I wasn't able to reproduce the crash, but it looks like it might have happened in an update. Disallowing autoreload during updates will probably fix things. 

I think we can close this.

**Closed by renpytom** 2021-05-22 00:38 UTC

**Comment by Gouvernathor** [comment] 2021-05-22 08:52
That one didn't occur when I was updating RenPy, just when I was switching themes. That crash was fixed by closing and reopening the launcher, whereas when I tried to update with autoreload enabled (willinly, for testing purposes) I had to reinstall renpy afterwards because it was plain broken.

I'll repost it here if a crash happens again after you last tweaks.
