### ISSUE TITLE
Error when fetching Android SDK list

### ISSUE THREAD

**Issue by bbs3223474** [renpy/renpy#737] opened 2015-09-14 13:10 UTC
Here's trackback:

Full traceback:
  File "game/android.rpy", line 445, in script
  File "F:\Ren'py_SDK_Nightly\renpy\ast.py", line 797, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Ren'py_SDK_Nightly\renpy\python.py", line 1448, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/android.rpy", line 447, in <module>
  File "F:\Ren'py_SDK_Nightly\rapt\buildlib\rapt\install_sdk.py", line 263, in install_sdk
    get_packages(interface)
  File "F:\Ren'py_SDK_Nightly\rapt\buildlib\rapt\install_sdk.py", line 186, in get_packages
    with open(plat.path("android-sdk/extras/google/play_apk_expansion/downloader_library/project.properties"), "r") as f:
IOError: [Errno 2] No such file or directory: "F:\\Ren'py_SDK_Nightly\\rapt\\android-sdk-r23/extras/google/play_apk_expansion/downloader_library/project.properties"

This happens when RAPT finished extract Android SDK and tried to fetch SDK lists.
Ren'py SDK version is 6.99.6.749

**Comment by renpytom** [comment] 2015-09-14 23:46
Does that file exist? 

I just tried it here, and it works for me. Does that file exist? 

If it doesn't, you can install it by hand. Go into rapt/android-sdk-r23, and run the SDK Manager program. Under extras, find "Google Play APK Expansion Librarty" and "Google Play Licensing Library." Tell it to install those, and then re-run install sdk.

**Comment by bbs3223474** [comment] 2015-09-16 04:48
Yes, problem solved after SDK downloaded by hand. But actually confused me at first.

**Comment by renpytom** [comment] 2015-09-17 00:30
I don't know what the problem is, but it didn't happen here. Network issues happen. I'm going to close this bug.

**Closed by renpytom** 2015-09-17 00:30 UTC
