### ISSUE TITLE
xfill + box_reverse has incorrect behavior

### ISSUE THREAD

**Issue by eliptus** [renpy/renpy#4765] opened 2023-06-22 09:13 UTC
# To Reproduce
With Ren'Py 8.1.1:
```
screen test():

    frame:
        background Solid("#d42abeb7") # Pink
        align (0.5, 0.5)
        padding (15,15)

        xysize (1600, 1000)
        has hbox
        box_reverse True

        frame:
            padding (0,0)
            background Solid("#18df398f") # Green

            xsize 100 # Takes 100px from hbox

        frame:
            padding (0,0)
            background Solid("#492ec5") # Blue

            xfill True # Gets remaining xsize = 1600 - 100 = 1500
```

# Expected Behavior

![192346810-4317144b-8bb9-4755-8225-8f4f130c9681](https://github.com/renpy/renpy/assets/290057/9153d71d-99f7-412e-a8c6-870b6edff253)

# Observed Behavior

![192344772-bd4c7aa3-7a8f-4479-8d99-905da7817375](https://github.com/renpy/renpy/assets/290057/96fb9bd3-c09a-44e2-ba27-0271808bcf2c)

**Comment by mal** [comment] 2023-06-22 09:42
While perhaps surprising, it is consistent with manually reversing the order of the `frame` blocks. Ren'Py takes a one-pass approach to layout for performance and code sanity reasons, and so the size of the green box is not known when the blue box is calculating it's width with `xfill`. You may consider using a `side` for such a layout which is better able to handle this sort of thing.

<details><summary>Example modified to use `side`</summary>

```diff
 screen test():

     frame:
         background Solid("#d42abeb7") # Pink
         align (0.5, 0.5)
         padding (15,15)

         xysize (1600, 1000)
-        has hbox
-        box_reverse True
+        has side 'r c'

         frame:
             padding (0,0)
             background Solid("#18df398f") # Green

             xsize 100 # Takes 100px from hbox

         frame:
             padding (0,0)
             background Solid("#492ec5") # Blue

             xfill True # Gets remaining xsize = 1600 - 100 = 1500
```
</details>

**Comment by eliptus** [comment] 2023-06-22 13:32
I don't agree with your characterization. I'd argue that it is a bug that it behaves the sames as manually reversing the order. The only value of having this would be to achieve the analogous of the behavior as left-to-right behavior in the right-to-left direction while maintaining the one-pass approach. What value is having it behave identically to manual reversal?

**Comment by shawna-p** [comment] 2023-06-22 13:38
This seems like a duplicate of #3999

**Comment by eliptus** [comment] 2023-06-22 13:41
The claim in #3999 is that this is a result in children are evaluated in one pass from top to bottom. This example shows that behavior being violated for `box_reverse`.

**Comment by eliptus** [comment] 2023-06-22 13:47
To preempt any similar claims, the documentation for `box_reverse` states that `will be filled right-to-left`.

It does **not** state that children are processed in reverse order, which is what responses seems to claim as the intended order.

**Comment by renpytom** [comment] 2023-06-23 04:45
I've decided to change the behavior of Ren'Py when it comes to box_reverse, as you can see in the associated commit. The goal is to make box_reverse more useful for right-to-left languages. (I've rethought the position I took in #3999.) 

Since this (though unlikely) might break working games, I'm targeting this at 8.2/7.7.

**Closed by renpytom** 2023-06-23 04:45 UTC
