### ISSUE TITLE
Importing python side packages causes issues due to wrong __file__ location.

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#4948] opened 2023-08-31 09:41 UTC
There is an issue when importing side packages that were installed into the `python-packages` folder of a game: Often these modules may look up their location using the `__file__` variable. But unexpectedly the variable doesn't point to the absolute path of the file it's called from. So those modules fail to load certain libraries for example. While `__file__` should return the absolute path in Python, there is some kind of relative path returned in this case.

(Renpy 8.1.2 nightly fix)

**Comment by mal** [comment] 2023-08-31 18:16
Duplicate of https://github.com/renpy/renpy/issues/4644.

**Comment by renpytom** [comment] 2023-09-02 02:43
Note that this likely represents an incompatibility with Ren'Py, as on some platforms (like android) files don't exist on disk.

**Closed** 2023-09-02 08:30 UTC
Labels: duplicate
