### ISSUE TITLE
 dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by hasufell** [renpy/renpy#311] opened 2014-03-01 15:24 UTC
Pretty low priority since I cannot reproduce any bugs that might be related to these warnings. Still, it would be good to take care of them (on Gentoo these are considered general QA issues which indicate that the package may exhibit random runtime failures).

Sure, you can compile with "-fno-strict-aliasing", but that is a _huge_ penalty and generally not advised even if we have compiler warnings.

Here are some references and possible solutions to this problem:
http://mail-index.netbsd.org/tech-kern/2003/08/11/0001.html
http://thread.gmane.org/gmane.linux.gentoo.devel/39495
http://gcc.gnu.org/bugs/#nonbugs_c

```
gen/pysdlsound.sound.c:2020:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/pysdlsound.sound.c:3756:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/pysdlsound.sound.c:3761:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/pysdlsound.sound.c:3778:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/pysdlsound.sound.c:3807:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/pysdlsound.sound.c:3980:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:14411:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:14426:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:14462:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:14802:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:14969:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15002:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15181:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15183:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15272:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15385:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:15455:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:16212:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:17083:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:17257:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:17580:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:21906:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:21991:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22193:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22198:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22211:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22216:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22229:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22255:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:22268:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:2557:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:2912:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:3318:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:5321:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.display.render.c:8629:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:10185:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:14662:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:14727:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:14884:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:14886:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:18222:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:18235:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:18248:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:2016:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:2020:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:2303:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:2362:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:3487:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4005:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4104:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4657:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4726:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4743:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4792:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4812:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:4951:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:5127:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:5139:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:5458:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:6391:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:6677:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:6805:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:6845:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:7221:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:7238:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:7633:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:8716:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:9045:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:9183:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gldraw.c:9820:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_fixed.c:2418:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_fixed.c:3143:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_fixed.c:4463:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_limited.c:1124:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_limited.c:3584:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_shader.c:1597:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.glenviron_shader.c:1836:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:17308:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:3117:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:3151:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:4216:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:4273:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:4283:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.gl.gltexture.c:4608:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.style.c:10825:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.style.c:3283:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.style.c:592:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:67309:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:67376:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:67963:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68003:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68347:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68360:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68569:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68582:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68863:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:68894:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:69265:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:69296:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:69667:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:69698:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70033:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70055:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70345:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70367:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70657:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.styleclass.c:70679:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.text.textsupport.c:2627:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.text.textsupport.c:6381:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gen/renpy.text.texwrap.c:2382:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```

**Comment by renpytom** [comment] 2015-02-07 00:57
I'm closing this because the problem isn't one I can fix - it needs to be fixed in our tooling.

**Closed by renpytom** 2015-02-07 00:57 UTC
Labels: long term
