### ISSUE TITLE
Windows refresh after change the size

### ISSUE THREAD

**Issue by PeterDorn** [renpy/renpy#4559] opened 2023-04-23 17:42 UTC
When windowed mode is used and the window is manually adjusted by the user, Ren'Py does not automatically update the width and height of the window. As a result, the hover effects of the buttons no longer fit the new window size. However, if the script is reloaded by pressing Ctrl+R, the window updates correctly

**Comment by lauwurence** [comment] 2023-04-23 20:41
Same thing happens with hyperlinks in the About menu.

Sometimes it works:
![image](https://user-images.githubusercontent.com/46109734/233865063-c97e4685-d263-443f-9576-274da74a6619.png)

Sometimes it doesn't:
![image](https://user-images.githubusercontent.com/46109734/233865093-32240d9a-9606-43c9-a109-6ac8c2ad75a3.png)

**Comment by Gouvernathor** [comment] 2023-04-23 21:06
I can't reproduce that on Windows.
However I've had a comparable bug in the past, where after hibernating and waking up again the window would show up with a transparent section on the bottom and right, and with the click being offset.
It turns out it was a GPU/drivers issue, so you should both probably update yours, and if it still glitches it may still be the drivers' fault.

**Comment by renpytom** [comment] 2023-04-23 21:08
I can't reproduce this one either. Can you post log.txt files from an instance where this happened?

**Comment by lauwurence** [comment] 2023-04-24 12:38
Sorry, I think I was wrong reporting my issue here. It's probably not related to game window, but to text hyperlinks.
Here I created a separate Issue: https://github.com/renpy/renpy/issues/4569

**Comment by renpytom** [comment] 2023-04-30 04:17
Closing, as I can't reproduce this.

**Closed by renpytom** 2023-04-30 04:17 UTC
Labels: can't reproduce
