### ISSUE TITLE
About the closing of Text Tags

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3926] opened 2022-08-31 17:44 UTC
Are there any special reasons for not self-closing text tags to be always manually closed?
We can use such self-closing tags as `{size=...}` without closing it, but if we try some custom tags (added with config.custom_text_tags) it will throw an error: 
`"Text ended while the '...' text tag was still open."`

I also tried to remove that `raise Exception` code from the engine and now it still works as it should, but without raising the error message.

**Comment by Gouvernathor** [comment] 2022-08-31 17:50
The issue is that it raises a lot of questions as to what happens in edge cases, for example when you use `extend` after a dialogue which has unclosed text tags. These edge case behaviors would have to be explored and documented, because we will then need them to behave exactly as they currently do between versions of renpy.
Also, it's good sometime to have a stricter syntax, because it's easier to report, understand and fix mistakes on the developer's end.

**Comment by via-my** [comment] 2022-08-31 18:06
Then why default text tags can be used without strict syntax?

**Comment by via-my** [comment] 2022-08-31 18:49
Maybe it will be better not to do that? :) 
Or at least add an ability to quickly disable that exception?
Some big games contain a huge amount of code that will need to be reviewed after such changes.

**Comment by methanoliver** [comment] 2022-08-31 19:32
Suggestion: Make lint check that every tag is closed, including the builtin ones, and complain, but change nothing otherwise.

Then, revisit the issue later. :)

**Comment by renpytom** [comment] 2022-09-02 02:23
I'm wondering if we should encourage a style where closing text tags at the start of the string is optional, while closing those that start in the middle of the string is encouraged. 

"{size=+20}I'm shouting!"

Doesn't really gain much by having the player have to write the close tag, does it?

**Comment by via-my** [comment] 2022-09-02 03:06
Then how would we treat such line? 

"{size=+6}Roar! {size=+12}ROAR!!"

**Comment by Gouvernathor** [comment] 2022-09-23 21:43
Policing the closing of builtin text tags would break this :
```rpy
e "{b}Here we..." # bold, of course
extend " go !{/b}" # still bold
```
This could be considered a feature. I don't consider it a _great_ feature, but considering it's sort of intuitive and already in, it's probably being used and shouldn't be removed. And there's no way to have different behaviors depending on a potential _future_ extend line.

That being said, I'm still frosty about extending that behavior further, namely to custom text tags. I explored the idea of enabling `{/}` for custom text tags, but contrary to builtin ones, intertwined custom text tags are working. Example : `"{big}B{rot13}I{/big}G{/rot13}"` (from [these](https://www.renpy.org/dev-doc/html/custom_text_tags.html#examples) custom text tags). So custom text tags and builtin ones will never work exactly the same way anyway.

**Comment by renpytom** [comment] 2023-01-04 05:45
I've decided to go with the behavior that non-self-closing text tags that are not explicitly closed are automatically closed at the end of the line. This matches the current behavior, except that the previous lint warning is generated, and custom text tags that previously caused an error now will not. 

This does mean that: 

```renpy
e "This is one {b}bold word in a sentence."
```

Will no longer report a lint error. I think that's fine, especially since it means it's now more convenient to write: 

```renpy
e "{b}I'm shouting at the top of my lungs."
```

**Closed** 2023-01-04 05:47 UTC
Labels: enhancement - hour
