### ISSUE TITLE
OpenGL rendering broken by Adrenaline 20.7.2 update

### ISSUE THREAD

**Issue by Queex** [renpy/renpy#2300] opened 2020-07-30 20:16 UTC
After updating to the latest AMD drivers, neither the Ren'py launcher nor any game renders correctly in OpenGL rendering mode.

This is probably going to be fixed in passing with 7.4, but I'm raising the issue so 7.4 can be tested for it when the time comes.

Radeon Version: 20.7.2 (2020.0711.1742.31878)
Driver Version: 20.20.01.09-200711a-357169E-RadeonSoftwareAdrenaline2020
2D Driver Version: 8.1.1.1634
OpenGL Version: 26.20.11000.14736

Example of improper rendering:
![image](https://user-images.githubusercontent.com/10655723/88970184-e0244200-d2a9-11ea-9899-6f735fa307bc.png)

**Comment by renpytom** [comment] 2020-07-30 23:08
I'll do my best to make sure it works, but I would recommend contacting AMD, since it's a bug in their drivers.

**Comment by Queex** [comment] 2020-07-31 15:46
I can confirm that rolling back drivers fixes it. Report to AMD made, and I'll try again when the next driver version emerges.

**Comment by renpytom** [comment] 2021-05-19 05:56
I'm hoping this was eventually resolved by AMD. I'll close this and your other issue, but feel free to reopen them if needed.

**Closed by renpytom** 2021-05-19 05:56 UTC

**Comment by Ecchithrwa** [comment] 2024-12-07 12:24
This is once again a problem on AMD drivers

**Comment by EchoFrost** [comment] 2024-12-07 20:58
Hi @Ecchithrwa! I'm doing some testing to try and replicate this issue- could you provide specific versions of the software you are running? (drivers and Ren'Py version like in the original issue report) 😊

**Comment by Ecchithrwa** [comment] 2024-12-24 10:58
> Hi @Ecchithrwa! I'm doing some testing to try and replicate this issue- could you provide specific versions of the software you are running? (drivers and Ren'Py version like in the original issue report) 😊

I don't have the specific driver installed currently but I can confirm the same issue on both a 6800XT GPU and a 780M (CPU with GPU built in) when using the latest driver 24.12.1 by AMD.. and also the past several months of drivers, lol. As far as renpy goes, it seems to happen on any version of Renpy since it launches by default with GL2 Renderer. If I hold shift I get the option to change it and it does run fine when using the ANGLE2 renderer. 

To add additional info, at least in my use case, this is only a problem when inside a virtual machine with GPU passthrough. It's a known AMD issue I've found out and not specific to renpy since AMD isn't passing through opengl and stuff correctly. Affects blender, minecraft, etc too apparently. 

That said, perhaps if Renpy defautled to the other renderer (what's the performance difference anyway?) then maybe it would be a good thing for edge cases like this. I can't see a performance difference one way or the other but maybe there is one for when it's running on Android, etc?

**Comment by renpytom** [comment] 2024-12-24 12:57
@Ecchithrwa 

If it's not specific to Ren'Py, then it probably makes sense to report it to AMD, not here. I'm not sure how I can do anything about broken drivers like this, asndf 

ANGLE introduces a translation layer from the OpenGL Ren'Py normally uses to DirectX calls, which do add overhead.
