### ISSUE TITLE
Updating game breaks some saves (8.1.0.23040504+ nightly)

### ISSUE THREAD

**Issue by mcordxeecee** [renpy/renpy#4515] opened 2023-04-06 01:02 UTC
Hey there! I recently applied what I thought was a small typo-fixing patch to my VN, but it's causing some issues for some readers.

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> File "renpy/common/00action_file.rpy", line 463, in __call__
> renpy.load(fn)
> Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
> File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
> python hide:
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\ast.py", line 1131, in execute
> renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\python.py", line 1061, in py_exec_bytecode
> exec(bytecode, globals, locals)
> File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
> python hide:
> File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
> ui.interact()
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\ui.py", line 299, in interact
> rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\core.py", line 3377, in interact
> repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\core.py", line 4258, in interact_core
> rv = root_widget.event(ev, x, y, 0)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\transition.py", line 53, in event
> return self.new_widget.event(ev, x, y, st) # E1101
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\screen.py", line 743, in event
> rv = self.child.event(ev, x, y, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1399, in event
> rv = super(Window, self).event(ev, x, y, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 279, in event
> rv = d.event(ev, x - xo, y - yo, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1399, in event
> rv = super(Window, self).event(ev, x, y, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 279, in event
> rv = d.event(ev, x - xo, y - yo, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 1175, in event
> rv = i.event(ev, x - xo, y - yo, cst)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\layout.py", line 279, in event
> rv = d.event(ev, x - xo, y - yo, st)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\behavior.py", line 1073, in event
> return handle_click(self.clicked)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\behavior.py", line 1008, in handle_click
> rv = run(action)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\display\behavior.py", line 329, in run
> return action(*args, **kwargs)
> File "renpy/common/00action_file.rpy", line 463, in __call__
> renpy.load(fn)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\loadsave.py", line 769, in load
> log.unfreeze(roots, label="_after_load")
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\rollback.py", line 1078, in unfreeze
> self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\rollback.py", line 889, in rollback
> self.load_failed()
> File "F:\SteamLibrary\steamapps\common\Misericorde Volume One\Misericorde Volume One\renpy\rollback.py", line 807, in load_failed
> raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
> Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

This is similar to issues I've seen with games that change their scripts too heavily, especially with choices and persistent variable and whatnot. My game does not have that: all that was changed was typos, no labels or anything were touched. I was also worried that the .rpycs weren't in old-game, but after a few volunteers tested it with beta versions with patches with different sets of .rpycs in the old-game folder, the problem persists.

Previous similar patches in the early release period did not cause these problems, but I am on a newer nightly now so I'm reporting it here just in case.

For now I've rolled the release back to the previous build made on 8.0.3.22090809. I want to patch the typos, but I don't want to force everyone to restart their saves. Is there something I'm missing here, perhaps a deeper bug than the "couldn't find a place to stop rolling back" message normally indicates? Thanks a ton!

**Comment by renpytom** [comment] 2023-04-06 02:28
This is almost always caused by a lack of .rpyc files in old-game, or other changes. 

If you didn't have .rpycs in old-game, you need to:

* Put them there.
* Delete all the .rpycs in game
* Force recompile. 

And that might resolve the issue.

**Comment by mcordxeecee** [comment] 2023-04-06 05:57
Oh, I hadn't tried force recompile! The old-game folder is full with the previous version's .rpycs, but I'll give that a shot and report back.

**Comment by mcordxeecee** [comment] 2023-04-06 06:29
Double-checking here, but I did have rpycs in old-game and force recompile seems to have been checked in the build settings. I've manually deleted the files from game and force recompiled before building this time, though--will post how it goes.

**Comment by mcordxeecee** [comment] 2023-04-06 23:24
An update on this: no matter what I seem to try, some saves just break. I have noticed through my own testing and asking users which saves have broken for them, they seem to be saves near jump labels. The easiest one I can replicate is right before the credits.

What I have tried:

-filling "old-game" with rpycs from the previous version
-filling "old-game" with rpycs from many versions ago
-the above, but with the added steps of forcing recompile and updating old-game through the build GUI

The same issue occurs on the same saves no matter what. The labels in question have not been altered since well before the oldest rpycs I have on hand. All that has changed is bits of dialogue. 

At this point, I am considering just updating the game like this and letting people know that if their save is broken to try an older one or start a new game and skip back to where they were previously. It's not ideal but I'm not sure what else I can try with old-game. Is there anything else worth trying?

**Comment by renpytom** [comment] 2023-04-06 23:29
I don't think so, assuming you've deleted (backing them up is better) the .rpcs from game/ to ensure that the regeneration uses the data from old-game. 

If you don't maintain .rpyc continuity throughout the game's releases, there may not be a great way to resolve the problem.

**Comment by mcordxeecee** [comment] 2023-04-06 23:42
Damn, that's a shame. I've tried lots of different sets of .rpycs and they all have the same problem. I wasn't vigilant enough about going from version to version during development, but I had enough backed up that I had hoped there'd be a set that would work. Oh well, learning experience!

**Comment by renpytom** [comment] 2023-04-06 23:43
I don't think there's anything else to do here, so I'm closing this issue.

**Closed by renpytom** 2023-04-06 23:43 UTC
