### ISSUE TITLE
Android 14; openGL built-in math functions bug when calculating with v_position variable

### ISSUE THREAD

**Issue by GitHub-Saga** [renpy/renpy#5642] opened 2024-07-20 01:28 UTC
I'm trying to create an animated shader ripple effect, with the ripples center determined by mouse position.
The shader works correctly on the PC Build (Win10 64-bit) and on my old phone running on Android 13.
But on my new phone running on Android 14, the shader calculations "freeze" when you reach a certain distance from the center. 
With "freeze" I mean the last calculated value after the certain distance remains the same for the rest of the shader.

 
```
renpy.register_shader("example.ripp", 

    variables="""
        uniform vec2 u_mPos;
        uniform sampler2D tex0;
        uniform vec2 res0;
        attribute vec4 a_position;
        varying vec4 v_position;
        attribute vec2 a_tex_coord;
        varying vec2 v_tex_coord;
        uniform float u_time;
        uniform vec4 u_viewport;
        uniform float u_t0;
        """,
    vertex_300="""
        v_tex_coord = a_tex_coord;
        v_position = a_position;
        """,
    fragment_300="""

        vec2 cPos;
        float cLength;
        vec2 uv;
        float A;

        cPos = u_mPos;
        A=1e-1;
        cLength = distance(v_position.xy, cPos);
        /*cLength = length(v_position.xy - cPos);*/

        float phi = cLength*5e-1 - 0.0*(u_time-u_t0)*100.0;
        uv =  v_tex_coord + vec2(0.0, A*sin(cLength)); 

        gl_FragColor = texture2D(tex0, uv, 0.0);
        """
    )
```

I have tried multiple different ways of calculations to reach the proper effect on Android 14, but to no avail. 
The code works as expected when you replace v_position with gl_FragCoord, but gl_FragCoord comes with alot of other issues (positioning, viewport size, window scaling, etc.). I have been able to deduce that the bug arises from the combination of v_position and the built-in math functions in openGL. I'm using Renpy 8.2.3. Ripples should fill the full viewport as it does on my PC and Android 13 phone, but ripples are limited to a certain area from the center point on my Android 14 phone, outside this area the rest of the texture just receives a constant offset.

**Comment by renpytom** [comment] 2024-07-20 02:54
Do you have something to force Ren'Py to draw the screen? By default, it may not.

**Comment by GitHub-Saga** [comment] 2024-07-20 13:04
Force Ren'Py to draw the screen? I don't quite understand what you mean.

After defining the shader, I define the transform and then add images at that transform.

```
init python:
    g0=time.time()
    renpy.register_shader("example.ripp", ...
    )

transform ripp(c=(0,0), f=0):
    shader "example.ripp"
    u_mPos (c)
    u_t0 (f)
    pause 0
    repeat

screen mocl():

    key "mousedown_1" action ShowMenu("main_menu")

    $ z = renpy.get_mouse_pos()
    $ g1 = time.time()-g0

    add Image("gui/test.png") at ripp(z, g1), center

screen main_menu():

    use mocl

    ## This ensures that any other menu screen is replaced.
    tag menu

```

**Comment by renpytom** [comment] 2024-07-20 16:35
So, I tried this on my phone (a pixel 7) and it works fine. 

The only thing I can think of is that a_position really isn't in any sort of sensible coordinate space. (It's relative to the texture itself.) If the device doesn't support a texture of that size (unlikely), it could split it up and maybe you'd get something like this? 

Other than that, I can't repeat this issue, and so it's hard to know what to do, except for making u_virtual_size available to a shader to make going from gl_Position or gl_FragCoord to virtual coordinates easier.

**Comment by GitHub-Saga** [comment] 2024-07-20 17:07
Does your Pixel 7 run on Android 14? If thats the case maybe exclude Android 14 being the issue. 
I test on Samsung devices S23 (Android 14) and an A53 (Android 13)

**Comment by renpytom** [comment] 2024-07-20 17:45
Yes, it runs on Android 14. 

You'd probably need to contact Samsung for support in the case where the issue is specific to your shader and their devices.

**Comment by renpytom** [comment] 2024-07-20 22:29
Added u_virtual_size, so I can close this.

**Closed by renpytom** 2024-07-20 22:29 UTC

**Comment by GitHub-Saga** [comment] 2024-07-27 00:04
Idk what phone emulator back-end renpy uses, I still double checked the functionaltity on some Android Studio emulators with different Android versions. The shader is shown correctly on there. 

I'll try contacting Samsung about this. Thank you for your help.
