### ISSUE TITLE
Major memory leak in minigame.

### ISSUE THREAD

**Issue by Sergemenog** [renpy/renpy#1436] opened 2018-04-24 15:10 UTC
Sorry for machine translate. I'm not native english speaker.

My minigame cause a memory leak. About 320MB RAM leak for less than 4 minute of gameplay in 60 FPS. More FPS == more leak. If tearing enabled, leaks about 1,3GB RAM for les than 4 minutes in 300 FPS.

Minigame is here: http://myfile.org/H11bjdeeb9/SSB-pc.7z

**Comment by renpytom** [comment] 2018-04-26 03:48
I can't debug this for you. 

It looks like you're keeping Renders alive for longer than a single frame by assigning them to structures reachable from global variables. If you do that, Ren'Py will leak memory.

**Comment by Sergemenog** [comment] 2018-04-26 12:07
> If you do that, Ren'Py will leak memory.

And this is not count as bug?

Documentations only says:
>A displayable object must be pickleable, which means it may not contain references to objects that cannot be pickled. Most notably, Render objects cannot be stored in a creator-defined displayable.

And I fulfilled these requirements.
By the way Renpy is not so fast to re-rendering the same render that was already rendered 16 milliseconds ago. Especially when you want to render something non-cacheable by Renpy itself.

**Comment by renpytom** [comment] 2018-04-26 13:17
That is for saving to work. Creator-defined displayables and renders are a whole different story - you need to make sure all the textures and renders you make are garbage collected after use. If you're hitting the 16ms window, you might also be creating a new texture each frame on the CPU, which is going to be a problem - and if you're then uploading it, the cause of your problem. 

Unfortunately, since I don't understand how your minigame works, it's hard to give advice. If it was smaller, perhaps I could figure out what's going on.

**Comment by Sergemenog** [comment] 2018-04-27 15:52
I began to split my mini-game into small simple elements to find a specific place of leak. And in the end, I got even more confused.
http://myfile.org/q5e9lbe2b8/tests.7z - contents 4 tests:
**test_memory_animation** - leak here.
**test_memory_animation_imcrop** - do not leak, but has same amount "alive Renders" "reachable from global variables" as **test_memory_animation**.
**test_memory_text_local** - do no leak, but "keeping Renders alive for longer than a single frame" inside creator-defined displayable (saving work).
**test_memory_text** - do in conventional way same thing as **test_memory_text_local**, but **16** times slower on my PC.

**Comment by Sergemenog** [comment] 2018-06-10 10:17
I workaround my memory leak issue by replacing all _img.render(0,0,0,0)_ with _renpy.load_surface(img)_.
Memory do not leak now, but application use 600MB RAM on start instead of 90MB.

**Comment by renpytom** [comment] 2018-07-04 16:54
I don't know what you did, but okay. I'm closing this now.

**Closed by renpytom** 2018-07-04 16:54 UTC
