### ISSUE TITLE
trasnsform wrongly allows and corrupts default parameters

### ISSUE THREAD

**Issue by RubenGarcia** [renpy/renpy#2990] opened 2021-08-22 12:28 UTC
```
init python:
  def f (trans, st, at, a):
        print (a)
        return 0

transform x (a=0)
  function renpy.curry(f)(a=a)

image i="i.png"

show i at x()
```

This code is accepted with latest renpy, but passes an Image as parameter a, instead of 0.
The documentation says: "The transform may have a list of parameters, which must be supplied when it is called."

- Are default parameters in transforms allowed? 
- If not, can this be detected at compile time?

**Comment by AndriWilford** [comment] 2021-08-22 16:04
This returns '0' for me, as intended:
```
init python:
    def f (trans, st, at, a):
        print (a)
        return 0
image i="arrow.png"
transform x (a=0):
    function renpy.curry(f)(a=a)
label start:
    e "You've created a new Ren'Py game."
    show i at x()
    e "Once you add a story, pictures, and music, you can release it to the world!"
    return
```

I played around adding globals called 'a' and such, to see if there was a context mixup, but couldn't cause any type than int and '0'.

**Comment by renpytom** [comment] 2021-08-22 21:46
I'm getting the same result as @AndriWilford when I test it here.

**Comment by RubenGarcia** [comment] 2021-08-23 05:20
I'll check it again. I had it working in the past, but I found a corner case. I probably pasted the wrong code.

**Comment by RubenGarcia** [comment] 2021-08-23 05:37
I cannot reproduce the issue anymore. I'll add to the documentation that optional parameters are allowed.

**Comment by RubenGarcia** [comment] 2021-08-24 14:51
https://github.com/renpy/renpy/pull/2996

**Comment by renpytom** [comment] 2021-08-24 18:14
Merged, and I'll close this issue.

**Closed by renpytom** 2021-08-24 18:14 UTC

**Comment by RubenGarcia** [comment] 2022-02-01 17:32
I found the corner case, see above.
