### ISSUE TITLE
$renpy.show_layer_at() breaks movement transitions

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2560] opened 2021-01-02 20:33 UTC
Using `$renpy.show_layer_at(CR(), layer='master', reset=False)` and
```
def aberration(child, **properties):
    return Fixed(
        At(child, Transform(xoffset=0, gl_color_mask=(False, True, False, True))),
        At(child, Transform(xoffset=-1, gl_color_mask=(True, False, False, True))),
        At(child, Transform(xoffset=1, gl_color_mask=(False, False, True, True))),
        fit_first=True,
        **properties)
CR = renpy.curry(aberration)
```
causes commands like `with move` and `with easeinright` on character sprites to stop working. (They just instantly appear.)
`with dissolve` and `with pixellate` still work as intended, though.

**Comment by Andykl** [comment] 2021-01-03 23:43
Duplicate of #1854. This matters to me so I will fix it most likely after 7.4.1

**Comment by BattleProgrammer-san** [comment] 2021-05-23 15:42
As of 7.4.4 this bug still persists. Any ETA on the fixing?

**Comment by Gouvernathor** [comment] 2021-12-27 16:04
Most likely duplicate of #2995, and fixed the same way.

**Comment by Andykl** [comment] 2021-12-27 18:45
Seems fixed. @kigyo, if the issue is not fixed in last RenPy release, feel free to reopen.

**Closed by Andykl** 2021-12-27 18:45 UTC
