### ISSUE TITLE
Major instability with Python 3.8 when attempting to create new projects

### ISSUE THREAD

**Issue by joshua-stone** [renpy/renpy#2412] opened 2020-10-19 04:56 UTC
I built the latest RenPy branch with Python3.8, and it seems to be capable of launching example projects. There is an issue when trying to create a new project though. Clicking `Create New Project`, `Continue` , then when typing anything into the project name field, shows this message:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "launcher/game/new_project.rpy", line 83, in script
    python:
  File "launcher/game/new_project.rpy", line 86, in <module>
    project_name = interface.input(
  File "launcher/game/interface.rpy", line 415, in input
    rv = renpy.call_screen(
AttributeError: module 're' has no attribute '_pattern_type'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "launcher/game/new_project.rpy", line 83, in script
    python:
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/ast.py", line 908, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/python.py", line 2104, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "launcher/game/new_project.rpy", line 86, in <module>
    project_name = interface.input(
  File "launcher/game/interface.rpy", line 415, in input
    rv = renpy.call_screen(
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/exports.py", line 2934, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 2885, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 3679, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/screen.py", line 720, in event
    rv = self.child.event(ev, x, y, st)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 245, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 245, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/layout.py", line 1004, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/behavior.py", line 1421, in event
    if isinstance(self.allow, re._pattern_type):
AttributeError: module 're' has no attribute '_pattern_type'

Linux-5.8.13-200.fc32.x86_64-x86_64-with-glibc2.2.5
Ren'Py 7.4.0.0
Ren'Py Launcher 7.4.0.0
Mon Oct 19 00:29:13 2020
```

This appears to be caused by [`_pattern_type` being renamed to Pattern](https://github.com/python/cpython/pull/1646/files#diff-daea55f2fca784d9a64ca8f190403904). Patching the affected lines does at least allow the editor to progress past the name creation screen.

Selecting a resolution and clicking Continue produces this next error:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "launcher/game/gui7.rpy", line 392, in script
    call screen choose_gui_color
  File "renpy/common/000statements.rpy", line 554, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "launcher/game/gui7.rpy", line 240, in execute
    screen choose_gui_color():
  File "launcher/game/gui7.rpy", line 240, in execute
    screen choose_gui_color():
  File "launcher/game/gui7.rpy", line 245, in execute
    frame:
  File "launcher/game/gui7.rpy", line 249, in execute
    window:
  File "launcher/game/gui7.rpy", line 250, in execute
    has vbox
  File "launcher/game/gui7.rpy", line 254, in execute
    frame:
  File "launcher/game/gui7.rpy", line 257, in execute
    has hbox:
  File "launcher/game/gui7.rpy", line 274, in execute
    frame:
  File "launcher/game/gui7.rpy", line 287, in execute
    use gui_demo(gui_color[0], gui_color[1], gui_color[2], display)
  File "launcher/game/gui7.rpy", line 157, in execute
    screen gui_demo(accent, boring, light, display):
  File "launcher/game/gui7.rpy", line 157, in execute
    screen gui_demo(accent, boring, light, display):
  File "launcher/game/gui7.rpy", line 159, in execute
    $ p = gui7.GuiParameters(
  File "launcher/game/gui7.rpy", line 159, in <module>
    $ p = gui7.GuiParameters(
TypeError: can't concat str to bytes

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "launcher/game/gui7.rpy", line 392, in script
    call screen choose_gui_color
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/ast.py", line 1955, in execute
    self.call("execute")
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/ast.py", line 1943, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 554, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/exports.py", line 2934, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 2885, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 3285, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 549, in visit_all
    d.visit_all(callback, seen)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 549, in visit_all
    d.visit_all(callback, seen)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 549, in visit_all
    d.visit_all(callback, seen)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/screen.py", line 432, in visit_all
    callback(self)
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/core.py", line 3285, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/screen.py", line 443, in per_interact
    self.update()
  File "/home/jstone/.var/app/org.renpy.RenPy/data/renpy/display/screen.py", line 631, in update
    self.screen.function(**self.scope)
  File "launcher/game/gui7.rpy", line 240, in execute
    screen choose_gui_color():
  File "launcher/game/gui7.rpy", line 240, in execute
    screen choose_gui_color():
  File "launcher/game/gui7.rpy", line 245, in execute
    frame:
  File "launcher/game/gui7.rpy", line 249, in execute
    window:
  File "launcher/game/gui7.rpy", line 250, in execute
    has vbox
  File "launcher/game/gui7.rpy", line 254, in execute
    frame:
  File "launcher/game/gui7.rpy", line 257, in execute
    has hbox:
  File "launcher/game/gui7.rpy", line 274, in execute
    frame:
  File "launcher/game/gui7.rpy", line 287, in execute
    use gui_demo(gui_color[0], gui_color[1], gui_color[2], display)
  File "launcher/game/gui7.rpy", line 157, in execute
    screen gui_demo(accent, boring, light, display):
  File "launcher/game/gui7.rpy", line 157, in execute
    screen gui_demo(accent, boring, light, display):
  File "launcher/game/gui7.rpy", line 159, in execute
    $ p = gui7.GuiParameters(
  File "launcher/game/gui7.rpy", line 159, in <module>
    $ p = gui7.GuiParameters(
  File "gui7/parameters.py", line 109, in __init__
TypeError: can't concat str to bytes

Linux-5.8.13-200.fc32.x86_64-x86_64-with-glibc2.2.5
Ren'Py 7.4.0.0
Ren'Py Launcher 7.4.0.0
Mon Oct 19 00:47:35 2020
```

**Comment by onitake** [comment] 2021-03-07 16:52
`TypeError: can't concat str to bytes` is caused by Python 3 making a strict distinction between Unicode strings (`str`) and byte strings (`bytes`).

Judging by the context here, `str` seems to be the sensible choice, so you should try to figure out where the byte string is coming from. I may be wrong of course.

This may also help: http://python3porting.com/problems.html#bytes-strings-and-unicode

**Comment by renpytom** [comment] 2022-03-20 02:09
This should be fixed in the nightly builds, now that Python 3 is supported by Ren'Py 8.0.

**Closed by renpytom** 2022-03-20 02:09 UTC
