### ISSUE TITLE
Viewport hbox with spacing causes some text to not wrap

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5712] opened 2024-08-17 13:26 UTC
Hi! 

I've been using Prerelease 8.3, and I noticed this issue with text-wrapping in hboxes with spacing inside viewports. Some text ends up not wrapping when it's too long to fit inside the hbox area inside the viewport area, and the text gets "cut off" early & you have to drag to the side on the viewport to read the rest of the text. 

An example:
![screenshot0001](https://github.com/user-attachments/assets/8da53b74-c5b5-4ae2-a910-5d0288f9c72f)

The same screen but launched in Ren'Py 8.2 instead:
![screenshot0319](https://github.com/user-attachments/assets/7b8216ec-f796-4f05-afd3-4d308e040228)

Here's a test project with the above screen: 
[Test Box Spacing Issue.zip](https://github.com/user-attachments/files/16645050/Test.Box.Spacing.Issue.zip)

**Comment by mal** [comment] 2024-08-17 17:53
Worth testing on a nightly build in case this is a duplicate of the already solved https://github.com/renpy/renpy/issues/5684.

**Comment by renpytom** [comment] 2024-08-19 05:32
Looks like it's been fixed.

**Closed by renpytom** 2024-08-19 05:32 UTC
