### ISSUE TITLE
Special characters In Windows username cause CTD when load the game.

### ISSUE THREAD

**Issue by decentmonkey** [renpy/renpy#2767] opened 2021-04-13 07:45 UTC
If Windows system username contains non-english characters, Ren'Py creating the save files at the game directory instead of "roaming".
After trying to load that created save file, the game crashing to the desktop.

Example username: Алёшö

**Comment by renpytom** [comment] 2021-04-13 13:34
Do you have a traceback.txt that goes with this? 

I believe this is only the case if the username contains characters that aren't representable in the system encoding, which it an issue that can't be addressed.

**Comment by Andykl** [comment] 2021-04-13 16:23
Алёшö is just such a case for sure. ё is Cyrillic symbol and ö is a Latin, not ASCII char so cannot exists in any Cyrillic codepage.
So, it's duplicate of #215

**Closed by Andykl** 2021-04-13 16:23 UTC

**Comment by decentmonkey** [comment] 2021-04-13 18:12
So, is it okay that the Chinese players and the other non-english can't play the games on Ren'Py?

**Comment by renpytom** [comment] 2021-04-13 18:52
No, but that isn't really the problem. The problem would be more that a Chinese user couldn't put Ren'Py in their User directory if their username contained Cyrillic, since (for the sake of argument), the Chinese encoding can't represent the Cyrillic character. I will fix  this eventually, but it's not a simple fix, which is why the issue has been around so long.

**Comment by decentmonkey** [comment] 2021-04-13 19:22
> No, but that isn't really the problem. The problem would be more that a Chinese user couldn't put Ren'Py in their User directory if their username contained Cyrillic, since (for the sake of argument), the Chinese encoding can't represent the Cyrillic character. I will fix this eventually, but it's not a simple fix, which is why the issue has been around so long.

Thank you for your answer.
Looking forward to development.
