### ISSUE TITLE
Order of background images incorrect when combining "add" and "scene"

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#1980] opened 2019-08-24 04:47 UTC
Hi, I'm not sure if this is a bug or just the way I'm doing things. Basically I am rendering many different backgrounds, and the issue is the last background will briefly flash after showing the first one again.

I am using a mix of `add` and `scene` renpy commands to render my backgrounds, but here is a simple demo of the issue I see:

```
screen black():
    add "images/bg black.jpg"

label blue():
    scene bg blue with fade
    "showing blue"
    return
 
label orange():
    scene bg orange with fade
    "showing orange"
    return

label start:

    show screen black
        
    $ x = 0
    while x < 5:
    
        "showing black"
        
        hide screen black
        call blue()
        call orange()
        show screen black
        
        $ x += 1
    
    return
```

Here I have code that will loop the interaction 5 times. This is the order in which I see things:

**1st iteration:**
- Black background shows
- "showing black" displays
- Blue background shows
- "showing blue" displays
- Orange background shows
- "showing orange" displays

^^ Expected order of background image transitions. (Correct)

**2nd iteration:**
- Black background shows
- "showing black" displays
- **_Orange background flashes briefly_**
- Blue background shows
- "showing blue" displays
- Orange background shows
- "showing orange" displays

^^ Incorrect order of background images... orange flashes briefly before transitioning into the blue. (BAD)

And then it **keeps repeating the 2nd iteration, where the orange flashes briefly, until the loop dies.** 

I also **tried hiding the orange background first**, before showing the black screen, so I have also tested the following snippet:

```
        hide screen black
        call blue()
        hide bg blue
        call orange()
        hide bg orange
        show screen black
```

However, instead of flashing the orange background, **renpy will now flash an empty transparent (grid) background briefly** before showing the blue background.

The same happens if I use `scene` without any parameters to force a cleanup of displayables:

```
        hide screen black
        call blue()
        call orange()
        scene
        show screen black
```
---

My expected outcome is what is described in the 1st iteration: black -> blue -> orange -> repeat. I think this may be a bug, but please correct me if I'm wrong.

**Comment by Belgerum** [comment] 2019-09-05 22:24
This isn't a bug.

What you are forgetting is that using `with fade`, if placed after a `show` or `scene` statement, will only affect the line of code it is placed on. In this case, that means that the lines of code before you fade in the new scene are executed instantaneously, and only the fade itself is executed with the transition.

Thus, at the start of the second loop, your orange background is still behind the black screen. The black screen is hidden instantaneously, revealing the orange background, and the transition only starts for the new transition from orange to blue.

If you want the fade transition to occur for both the hiding of the screen AND the new scene, then the transition has to be on it's own line of code, to show that it should be executed for everything since the last interaction.

A version of the code that should work as intended would be:

```
screen black():
    add "images/bg black.jpg"

label blue():
    scene bg blue
    with fade
    "showing blue"
    return
 
label orange():
    scene bg orange
    with fade
    "showing orange"
    return

label start:

    show screen black
        
    $ x = 0
    while x < 5:
    
        "showing black"
        
        hide screen black
        call blue()
        call orange()
        show screen black
        
        $ x += 1
    
    return
```

**Comment by renpytom** [comment] 2019-09-08 04:37
I think this has been answered, so I'm closing it.

**Closed by renpytom** 2019-09-08 04:37 UTC
