### ISSUE TITLE
"Launch Project" doesn't work.

### ISSUE THREAD

**Issue by koorsy** [renpy/renpy#4708] opened 2023-06-07 22:36 UTC
Hi again. I had given up, but i decided to try again.

First of all, sorry for my english, i'm not fluent. When i press the "launch project" buttom on the launcher nothing happends. A loading screen shows but then the main page of the launcher appears again. I've tried to restart my notebook, change the language, download other versions (including the nightly fix) and nothing works. I've tried to launch the projects that i've created and the tutorial one, but none worked.

I would be so grateful if someone could help me. Thank you.

**Comment by renpytom** [comment] 2023-06-11 01:17
Can you create a new project in Ren'Py 8.1.1, and see if the issue is fixed?

**Comment by renpytom** [comment] 2023-06-17 14:27
Closing this. Feel free to re-open if it's present with a new project in 8.1.1.

**Closed by renpytom** 2023-06-17 14:27 UTC

**Comment by koorsy** [comment] 2023-06-17 20:28
> Closing this. Feel free to re-open if it's present with a new project in 8.1.1.

Hi! I'm really sorry for not answering, i got really busy with my studies and just got some free time now. I'm downloading it right now and will try it, i hope it works. Thank you so much!
