### ISSUE TITLE
Blend Functions "min" alpha bug

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5699] opened 2024-08-11 10:52 UTC
Using the "min" blend function in Ren'Py 8.2.3 causes the alpha component to be black:

```renpy
    show eileen happy:
        blend "min"
```

![2024-08-11 05_38_07-Window](https://github.com/user-attachments/assets/fad84c29-b2bc-4843-9ce3-175c03527ad4)

The other default functions work as intended.

This also happen if you use it in a `layeredimage`:

```renpy
        attribute worried:
            "eyebrows worried" blend "min"
```

The custom **"darken" blend mode** has the same problem. Both "darken" and "min" has in common the `GL_MIN` function so maybe that's related to the problem. I tested with other custom blend modes like "screen" or "lighten" and works fine.

```renpy
init python:
    from renpy.uguu import GL_FUNC_ADD, GL_ONE, GL_ONE_MINUS_SRC_ALPHA, GL_MIN, GL_ONE_MINUS_DST_COLOR, GL_MAX

    ## (rgb_equation, src_rgb, dst_rgb, alpha_equation, src_alpha, dst_alpha)
    config.gl_blend_func["screen"] = (GL_FUNC_ADD, GL_ONE_MINUS_DST_COLOR, GL_ONE, GL_FUNC_ADD, GL_ONE, GL_ONE)
    config.gl_blend_func["lighten"] = (GL_MAX, GL_ONE, GL_ONE, GL_FUNC_ADD, GL_ONE, GL_ONE_MINUS_SRC_ALPHA)
    config.gl_blend_func["darken"] = (GL_MIN, GL_ONE, GL_ONE, GL_FUNC_ADD, GL_ONE, GL_ONE_MINUS_SRC_ALPHA)
```

Use case: I wanted to use "darken" in the eyebrow layer of my sprite so it blends better with the hair.

**Comment by Gouvernathor** [comment] 2024-08-11 11:43
That's most likely related to the alpha-premultiplication, which turns the color values to 0 when alpha is 0.

**Comment by renpytom** [comment] 2024-08-11 15:20
I'm pretty sure it is alpha premultiplication, so I've fixed this in f0a86c2a9 by writing a bit of documentation. It is probably a bad idea to use blend with a displayable that isn't opaque, as it's hard to wrap your head around the result. 

Alpha premultiplication is necessary to get things like window scaling right, so it's not going away - it's something we have to live with.

**Comment by renpytom** [comment] 2024-08-11 19:05
Yes. What you want to do is to make sure the mask has 100% alpha. That will then cause the colors to bring properly with the underlying image. Pixels that are transparent can be white.

**Comment by Gouvernathor** [comment] 2024-08-11 21:13
Maybe if it's just about fixing the pixels that are 100% transparent, a solution could be to apply a transform that adds a #fff or #000 solid underneath (depending on the targeted math result), using some sort of Fixed, that way the whole thing renders opaque and neuters whatever alpha premultiplication.

**Comment by renpytom** [comment] 2024-08-11 22:50
> > Maybe if it's just about fixing the pixels that are 100% transparent, a solution could be to apply a transform that adds a #fff or #000 solid underneath (depending on the targeted math result), using some sort of Fixed, that way the whole thing renders opaque and neuters whatever alpha premultiplication. And then the blend applies.
> 
> If I get you right, that would be the equivalent of using a white background on the layer. I did that and it resolved the black pixels problem, however, since the semi-transparent colored pixels on the border are now mixed with white the result is a different color and the blend does not look as intended and is not useful.

Are you using min or multiply here? In both cases, the results should be correct. White is always greater than any other color, so it will always take the other color except when the mask has a different color. Similarly, for multiply. Multiplying with right will just produce the original color.

**Comment by Gouvernathor** [comment] 2024-08-11 22:52
For the areas that were fully transparent, yes. But for the semi-transparent parts, the boundaries, mixing with white changes the actual color.

Maybe the solution then would be a shader that turns only the pixels that are fully transparent, solid white ? and pass that operation before the blend applies somehow ?

**Comment by renpytom** [comment] 2024-10-31 05:31
I'm closing this, since I think min is working as designed - it's just not all that useful.

**Closed by renpytom** 2024-10-31 05:31 UTC
