### ISSUE TITLE
Feature Request: Automated testing

### ISSUE THREAD

**Issue by a2937** [renpy/renpy#3198] opened 2021-12-24 18:11 UTC
I would be interested in seeing a way to test RenPy code more efficiently than just enabling debug features and manually editing variables and jumping around in a debug menu. Pytest or another similar library for continuous integration with a button and folder available in the project would be perfect. Here's how I imagine it will work; Renpy converts the code into valid python first than the unit tests proceed to get ran with results returned. 

I have seen an plugin for Renpy that surprisingly has unit testing available. Perhaps Renpy itself can add the tox package so we have that functionality out of the box.

[Renpy plugin using Tox](https://github.com/jsfehler/renpy-encyclopaedia)
[Tox](https://tox.wiki/en/latest/)

**Comment by uyjulian** [comment] 2021-12-25 21:36
You can automatically lint Ren'Py projects on each commit using Github Actions. <https://github.com/ProjectAliceDev/renpy-lint-action>

I don't think it would be a good idea to add additional libraries to Ren'Py unless Ren'Py will use it internally.

**Comment by renpytom** [comment] 2021-12-30 06:12
I'm going to close this, as I don't believe this is going to be a particular feature. There is an automated functional testing framework inside Ren'Py, but it needs to be brought up to date and documented. (It's in the renpy.test module.)

**Closed by renpytom** 2021-12-30 06:12 UTC

**Comment by jsfehler** [comment] 2021-12-30 19:33
@a2937 As the author of that repo, I'll elaborate a bit for you.

Tox is a tool to create reproducible jobs inside a virtualenv. It's very useful for testing, especially if you need to handle multiple python versions and/or environments. eg: (linux, win, osx) or (chrome, firefox). It's not the sort of thing you'd bundle with ren'py (or any app), but also nothing is stopping you from using it alongside ren'py.

The unit tests in renpy-encyclopaedia are written in plain python because renpy-encyclopaedia is written in plain python. As part of the build process, the contents are the .py files are dumped into an rpy file. The alternative would be to call pytest from inside ren'py, something I haven't tried. None of the unit tests in renpy-encyclopaedia interact with ren'py or the UI.

I built that plugin with a high degree of separation between the logic and UI. It's also something that doesn't have any heavy requirements on renpy itself. You could probably run renpy-encyclopaedia in plain python without too many changes and plug it into tkinter or whichever GUI you want. This is what made unit testing easy and fairly comprehensive. Even then, there's still some renpy parts I used which had to be mocked out in the unit tests, like the Action class.

I'd bet this is the exception rather than the rule. A lot of the things people do with ren'py only make sense from inside ren'py. You can definitely write code in such a way that you separate the parts that need ren'py from the parts that don't, but that's going to depend on the project.
