### ISSUE TITLE
[7.4.9.2130] Cannot convert ATLTransform to renpy.display.render.Render

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3070] opened 2021-10-04 02:52 UTC
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 91, in script call
    call expression state from _call_expression
  File "game/story/script.rpy", line 497, in script
    er b_Frown "Ajetreadas, no tengo tiempo para descansar. Y durante las noches me quedo despierta para estudiar."
TypeError: Cannot convert ATLTransform to renpy.display.render.Render

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 91, in script call
    call expression state from _call_expression
  File "game/story/script.rpy", line 497, in script
    er b_Frown "Ajetreadas, no tengo tiempo para descansar. Y durante las noches me quedo despierta para estudiar."
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/character.py", line 1223, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/character.py", line 875, in do_display
    **display_args)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/character.py", line 621, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/display/core.py", line 3834, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "/home/neyunse/renpy-7.4.6-sdk/renpy/display/core.py", line 2559, in draw_screen
    renpy.display.draw.draw_screen(surftree)
  File "gl2draw.pyx", line 814, in renpy.gl2.gl2draw.GL2Draw.draw_screen
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 871, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
  File "gl2draw.pyx", line 862, in renpy.gl2.gl2draw.GL2Draw.load_all_textures
TypeError: Cannot convert ATLTransform to renpy.display.render.Render

Linux-5.11.0-37-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.9.2130
Rosas de amor 1.0.0
Sun Oct  3 23:48:47 2021
```
The error seems to be in this line
```
show Eri b_Frown at truecenter
```

**Comment by renpytom** [comment] 2021-10-04 02:59
Hm... this is really hard to diagnose from the tracebakck. Can you break this out into a small game that shows the problem?

**Comment by renpytom** [comment] 2021-10-04 02:59
Also, if you have a creator-defined displayable, that's most likely the cause.

**Comment by Neyunse** [comment] 2021-10-04 03:23
> Also, if you have a creator-defined displayable, that's most likely the cause.

The strange thing is that it never happened to me

**Comment by Neyunse** [comment] 2021-10-04 03:26
> Hm... this is really hard to diagnose from the tracebakck. Can you break this out into a small game that shows the problem?

I have just created a clean project and I can't replicate it... I will therefore close this report.

**Comment by Neyunse** [comment] 2021-10-04 03:32
or maybe is this
```
image Eri c_Frown = ConditionSwitch(
    # Static
    "persistent.memories_enabled", At("images/Sprites/01/Casual/Aiko_Casual_Frown.png",ajust),
    "not persistent.memories_enabled", At("Memories/Sprites/01/Casual/Aiko_Casual_Frown.png",ajust),

    )
transform ajust:
    yoffset 81
    size(561 , 1105)
    on show:
        alpha 0.0
        linear 1.0 alpha 1.0 ```

**Comment by Neyunse** [comment] 2021-10-04 03:35
Yes, it turns out that ConditionSwitch is apparently the problem. @renpytom

**Comment by rex-nihilo** [comment] 2021-10-04 14:39
I have the same issue with 7.4.9.2130 prerelease.
No problem with 7.4.9.2105 and previous versions.

Like @Neyunse I also use images with ConditionSwitch and Transform.

**Comment by renpytom** [comment] 2021-10-04 14:49
A mistake on my part, it'll be fixed in the next nightly/prerelease.

**Closed** 2021-10-04 14:49 UTC
