### ISSUE TITLE
Sometimes things 'move' by one pixel then return. Align property rounding error?

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3776] opened 2022-07-19 00:09 UTC
As in the title, I noticed this on many different occasions over the past year. In the attached video, focus on the game title, it will move up and down by a pixel, my guess is that it's because of rounding. It uses aligns, so that might be the cause.  All other pixels are pre-counted at init.

It might be noteworthy that the game is windowed. I tried resizing the window, and it seems to have stopped sometimes, so perhaps the width or height of my window was uneven, and it was the cause of the rounding issue. 

After using the 'Window' setting (renpy default), it started again. My screen is 3840x2160, the game is 1920x1080, and the window size when the issue occurs is 2833x1666.

https://user-images.githubusercontent.com/78815540/179636164-ac26f3eb-aaf6-4ecd-ab5c-e7577d2fd08b.mp4

screen:
```
define gui.main_menu_outline = calc_gui(8)
define gui.main_menu_textsize = calc_gui(120)
define gui.main_menu_size = calc_gui(280)
define gui.main_menu_title_outline = calc_gui(16)

screen main_menu():

    ## This ensures that any other menu screen is replaced.
    tag menu

    style_prefix "main_menu"

    add gui.main_menu_background

    use supporters id "support"

    use web_messages(web.notifications["messages"])

    ## This empty frame darkens the main menu.
    #frame:
    #    pass

    # Game Title
    text "[config.name!t]":
        style "main_menu_title"
        font fonts["imFell"]
        size gui.main_menu_size
        outlines [ (absolute(gui.main_menu_title_outline), "#000000", absolute(0), absolute(0)) ]
        xalign 0.5
        yalign 0.9
        color "#ac0707"
```

I didn't attach the rest as it should be irrelevant.

**Comment by renpytom** [comment] 2022-07-20 05:42
Could you make a small example (ie, not your entire game) that demonstrates this problem? From the video, it's hard to tell if this a problem with Ren'Py or something in your game.

**Comment by Victorius-Astral** [comment] 2022-07-20 09:55
> Could you make a small example (ie, not your entire game) that demonstrates this problem? From the video, it's hard to tell if this a problem with Ren'Py or something in your game.

Sure, here it is. I tried various stuff, and it seems it happens only on this font, and it also appeared on a frame in the new project, while it didn't in my game (I copied the code and removed most things, so only the issue related are kept)

Whenever the message in the top-right corner changes (Show action) with dissolve, this appears, but only on the second font and the messages window. 

**_Not using transition causes it to work, so it seems to be done by show with dissolve._**

https://user-images.githubusercontent.com/78815540/179952812-e1d7ec17-6d41-4ba3-bf0b-bf74d0493bfa.mp4

The whole code is in script.rpy

[game.zip](https://github.com/renpy/renpy/files/9148635/game.zip)

```
screen main_menu():

    ## This ensures that any other menu screen is replaced.
    tag menu

    add "#9c9c9c"

    #######################
    ### This causes BUG ###
    use web_messages(["TEST 1", "TEST 2"])
    #######################

    ## This empty frame darkens the main menu.
    frame:
        style "main_menu_frame"

    ## The use statement includes another screen inside this one. The actual
    ## contents of the main menu are in the navigation screen.
    use navigation

    text "Bugged":
        style "main_menu_title"
        size 140
        outlines [ (absolute(8), "#000000", absolute(0), absolute(0)) ]
        xalign 0.5
        yalign 0.9
        color "#ac0707"
        font "IMFellDWPica-Regular.ttf" # FONT BUG? Window flickers too, though.

    text "Not Bugged":
        style "main_menu_title"
        size 140
        outlines [ (absolute(8), "#000000", absolute(0), absolute(0)) ]
        xalign 0.5
        yalign 0.7
        color "#ac0707"




#######################################################################
#### IT CHANGES THE MESSAGE, AND DURING THIS CHANGE THE BUG OCCURS ####
#######################################################################
init python:

    def web_messages_page(current, last):
        if current + 2 > last:
            return 0

        else:
            return current + 1

screen web_messages(messages):
    style_prefix None

    default current_page = 0
    default pages = len(messages)

    # AUTO CHANGE PAGES
    timer 1.0 repeat True action [
        Show("web_message", dissolve, messages[web_messages_page(current_page, pages)]),
        SetLocalVariable("current_page", web_messages_page(current_page, pages)),
        ]

    timer 0.01 action Show("web_message", dissolve, messages[current_page])

    hbox:
        align (0.98, 0.01)

        vbox:

            #######
            # BUG #
            frame:
                background "#000C"
                xysize (450, 300)
                padding (20, 32, 20, 16)
            ######

    on "hide" action Hide("web_message")
    on "replaced" action Hide("web_message")

###################################
### SHOWING THIS CAUSES THE BUG ###
###################################
screen web_message(message):
    tag webmessage

    frame:
        background None
        xysize (450, 300)
        padding (20, 32, 20, 16)
        margin (0, 0)
        align (0.98, 0.01)

        # DISPLAY CURRENT MESSAGE
        text message text_align 0.5 xalign 0.5 yalign 0.05 size 33
```

**Comment by renpytom** [comment] 2022-07-28 01:09
I'm unable to repeat this with your game.zip.

Here's the line showing the sizes I tested against, from log.txt.

Screen sizes: virtual=(1920, 1080) physical=(2833, 1666) drawable=(2833, 1666)

This matches what you have above, but I'm not able to repeat this.

**Comment by renpytom** [comment] 2022-08-07 19:42
Since I can't reproduce, I'm closing this issue until more information comes to light.

**Closed** 2022-08-07 22:22 UTC
Labels: can't reproduce
