### ISSUE TITLE
[Bug] RenPy project loader unresponsive to first click after window losing focus.

### ISSUE THREAD

**Issue by CTXC** [renpy/renpy#3149] opened 2021-11-30 20:38 UTC
Windows Version (64-bit), On Windows 10

The project loader, main program, will indicate that it is "in focus" as menu-items "glow" showing them in "hover" state. However, the first click on the window is being "discarded" or "interrupted" by something in the GUI. Making it unresponsive to the first click. However, this is ONLY to the GUI, as clicking "Close" or any "window buttons", does not have this ghost-click effect.

To reproduce: Open Renpy. Open Some other program with a window. Do anything within the other open window, so Renpy has "lost window focus". Now move your mouse over any label in the renpy screen and you can see it indicates "hover" state by highlighting the hovered text. Try to click that label and nothing happens. Click it again, and it acts as intended.

Expected operation: Do the above, but the first click should be acted upon, not disappearing or being discarded or consumed by some ghost-issue.

Relatable internal issue: Displaying a screen with a "show screen MyScreen" from "label start:" and then hiding with an "action Show('MyOtherScreen')", having a similar tagged-ID screen, has a similar issue when the second screen is closed with an "action Hide()". The second screen closes, but there is a "ghost-click", before dialogue will continue. It is as if the first screen is still there, just not seen, consuming the click. (Only resolved by "calling" the screen instead of using "show screen MyScreen")

**Comment by Andykl** [comment] 2021-11-30 21:16
Duplicate of #3112.
You can use `config.mouse_focus_clickthrough = True` currently avaliable in 7.4.11 prerelease.

**Comment by CTXC** [comment] 2021-11-30 21:17
How do you use this in the Renpy program itself, the "RenPy Launcher"?

**Comment by Andykl** [comment] 2021-11-30 22:19
In 7.4.11 RenPy launcher will pass click event through by default. https://github.com/renpy/renpy/commit/b7e53ccf7462eb774012600ffd3ff67a55d56c58

**Comment by renpytom** [comment] 2021-11-30 22:21
I'm not sure this was merged into 7.4.11, but I'll make sure it is.

**Comment by renpytom** [comment] 2021-12-02 04:12
This is in the 7.4.11 prerelease.

**Closed by renpytom** 2021-12-02 04:12 UTC
