### ISSUE TITLE
Shader access to model's render size

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5588] opened 2024-06-24 20:18 UTC
I'm interested in developing a special LOD-like shader (I assume a shader is the best way to implement this) that switches between two different textures depending on a comparison between the displayable's rendered (virtual) size and initial (actual) size, but I have no idea if this is possible in Ren'Py. I'm pretty sure I just need the post-`Transform` virtual size, but despite poring over the documentation I can't figure out if this information is ever passed or exposed to the shaders at any point.

Is what I'm asking for even possible? If so, how do I get it? Sorry if this is a stupid question.

**Comment by renpytom** [comment] 2024-06-24 20:45
Note that transformations are applied to the displayable, and the displayable doesn't know what size it's being transformed to.

**Comment by paranormalized-encryptid** [comment] 2024-06-24 21:07
> i think what you want to look into are the `u_model_size` and `tex0`/`tex1` uniforms

No, those uniforms record the initial size, not the virtual size.

> Note that transformations are applied to the displayable, and the displayable doesn't know what size it's being transformed to.

Yes, that's the problem. I wasn't sure if the ultimate render size might get passed back down to the shader at some point, maybe using the shader part priorities (which admittedly I don't really understand - just guessing how they work). Is there any way to achieve what I want, with or without shaders?

**Comment by I-Have-No-Idea-What-IAmDoing** [comment] 2024-06-24 21:57
You might be able to use a creator defined displayable to switch rendering between 2 child displayable depending the conditions?

**Comment by paranormalized-encryptid** [comment] 2024-06-24 23:17
> You might be able to use a creator defined displayable to switch rendering between 2 child displayable depending the conditions?

To do that I would have to identify and obtain the render size of the displayable by manually iterating through the parent-child (and parent-mask etc.) chain of every displayable currently showing on every visible `layer` and `screen` until the instance finds itself, which is not really doable. Especially as I would want the effect to be applied to a large number of displayables, some of which will be shown as duplicates (so no unique IDs for easy lookup), across every single `layer` and `screen`. Even then it wouldn't work because the target displayable could be nested somewhere inside another displayable which doesn't happen to save the rescaled size of that specific child/grandchild/etc. to itself somewhere. LOD-like effects really need to occur at the render level.

**Comment by renpytom** [comment] 2024-06-25 01:42
I think it's probably fair to say that LOD effects aren't something Ren'Py supports. What are you trying to do?

**Comment by paranormalized-encryptid** [comment] 2024-06-25 02:05
Whenever a displayable's render width and/or height <= 0.5 the initial size I was hoping to switch to a modified texture with fewer details so that entities scale better visually. There's a lot of size variation in my game, so it was something I felt was worth exploring.

**Comment by renpytom** [comment] 2024-06-30 03:00
I don't see a great way of doing this. A displayable in Ren'Py can be shown multiple times at multiple sizes, so there's no one render size. 

The problem is Ren'Py does little to nothing involving level of detail itself - all of that is done on the GPU. So you might be able to write a shader to select between two textures, though I don't really see an obvious way how - you might be able to apply u_transform, which is the transform from virtual coordinates to the OpenGL coordinate space, and somehow use that to make your choice. 

I don't have a plan to implement anything in engine, so I'm closing this issue. If you have a concrete suggestion, let me know.

**Closed by renpytom** 2024-06-30 03:00 UTC

**Comment by paranormalized-encryptid** [comment] 2024-06-30 10:18
That's fine, PyTom. I wondered because of the presence of variables like u_lod_bias but your explanation makes sense. It isn't an absolute necessity for us, though I might revisit the idea in future and try to get something working.
