### ISSUE TITLE
Baking dialogue IDs into the game

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#4670] opened 2023-05-27 04:57 UTC
Just like how you can add 'from' clauses to your calls in the SDK, would it be possible to add a button to bake the dialogue IDs into the game? The use case for this is, for example, fixing a typo in your game whilst having more than one language, currently, whenever you fix a typo, you have to regenerate the translations and then go one by one, file by file, replacing the new string with what was previously there (because more often then not, a typo in the scripts will not be present in its translation). This can be very tiresome, so I'd appreciate it if this was added or an alternate solution was provided.

Thank you very much.

**Comment by mal** [comment] 2023-05-27 11:26
Reads like a duplicate of #4156.

I believe the expected way to handle this is to add the `id` clause yourself when correcting a typo, thus removing the need to update each translation file, with the `id` being easily retrieved from any one of the translation files.

**Comment by renpytom** [comment] 2023-05-29 06:04
Closing as duplicate. I may be open to a command line program that does this. I don't want to leave such and obvious footgun in Ren'Py.

**Closed by renpytom** 2023-05-29 06:04 UTC
Labels: duplicate
