### ISSUE TITLE
After selecting output audio device in Windows 10, renpy crashes

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3200] opened 2021-12-26 10:19 UTC
Steps to reproduce:
* Launch Tutorial game (default game in Ren'Py)
* Press Shift+R hotkey
* Game has been reloaded
* Select output device
![image](https://user-images.githubusercontent.com/4878139/147405176-9b85f5f5-e978-4694-966d-a666449d8d8c.png)
* Game has been crashed

Also, it seems to me that this can happen at an incomprehensible moment if you adjust the volume of the sound by the Windows 10 system

**Comment by Andykl** [comment] 2022-04-03 20:51
I can't reproduce it on Windows 10 Pro 19044.1586

**Comment by renpytom** [comment] 2022-04-03 20:54
This seems very system specific, and also only happens on shift+R. I wasn't able to repeat it in initial testing, also - so I'll close this unless it can happen reliably.

**Closed by renpytom** 2022-04-03 20:54 UTC
