### ISSUE TITLE
deprecate `future`

### ISSUE THREAD

**Issue by a-detiste** [renpy/renpy#5303] opened 2024-01-24 19:33 UTC
`future`will be removed from Debian anytime soon and won't be in Ubuntu 24.04
`six`will linger for a few years more.

If python 2+3 compatibility is still needed, please move what could be to `six` library instead

I can provide a PR

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059934

```
$ grep ' future' -r | grep 'import '
launcher/game/choose_theme.rpy:    import future.utils
module/setup.py:import future
module/generate_styles.py:from future import standard_library
renpy/common/00updater.rpy:    import future.utils
renpy/loadsave.py:from future.utils import reraise
renpy/compat/__init__.py:import future.standard_library
renpy/compat/__init__.py:import future.utils
renpy/compat/__init__.py:from future.builtins import chr
renpy/execution.py:from future.utils import reraise
renpy/audio/audio.py:from future.utils import raise_
distribute.py:import future.standard_library
distribute.py:import future.utils
```

**Comment by renpytom** [comment] 2024-01-24 20:15
We can do this after Ren'Py drops Python 2 support (after May).

**Comment by a-detiste** [comment] 2024-01-24 20:21
OK ... I'm waiting for a 8.2.1 ...

**Comment by renpytom** [comment] 2024-01-24 20:47
Almost certainly 8.3 or 8.4.

**Comment by a-detiste** [comment] 2024-01-24 20:54
I mean I'm waiting for a 8.2.1 where I would patch-out `future` and replace renpy/compat/__init__.py   by a stub.

**Comment by a-detiste** [comment] 2024-01-24 20:56
Hinting me some games that actually require this compatibility would help me greatly

**Comment by renpytom** [comment] 2024-01-24 21:02
Ren'Py will still support Python 2 until May, so we can't patch it out until then.

**Comment by a-detiste** [comment] 2024-01-24 21:06
I know and I understand your release planing, I mean it will be patched out in Debian (and Ubuntu etc...)

**Comment by eli-schwartz** [comment] 2024-02-02 04:56
@renpytom the issue is not actually about python2 at all.

The issue is that the renpy project made the decision some time back to replace the use of `six` with `renpy.compat` and `future`. Unfortunately, `future` doesn't actually work with python 3.12 which means that renpy cannot be installed on systems that use python 3.12, which is rather problematic since the entire original point of using `future` was supposed to be enabling python3 to work and now it turns out that that's not particularly reliable.

What would be appreciated is a commitment to repeal this mistake, and switch back from `future` to `six`. The `six` library supports both python 2.7 and 3.12 (and 3.13 if you need that).

**Comment by renpytom** [comment] 2024-02-02 15:21
I don't plan to make that change, as future was the key to enabling a port to Python 3 that didn't make me want to vomit, like six did. 

There seems to be a Python 3.12 compatible version of future at https://github.com/PythonCharmers/python-future/pull/632  . That being said, I will probably drop future entirely after May. 

There are also several Python 3.12 constructs that Ren'Py doesn't analyze correctly yet, so right now it's not a supported version.

**Comment by lanodan** [comment] 2024-03-03 06:30
@renpytom
> There seems to be a Python 3.12 compatible version of future at PythonCharmers/python-future#632 .

Doesn't seems to actually work as the testsuite of future-1.0.0 doesn't passes with 3.12. (You can see the errors at https://github.com/PythonCharmers/python-future/pull/635 )
But yeah, it's a bit moot if RenPy itself doesn't supports py3.12 anyway.

@Gouvernathor
> Creators and players should still be fine on any platform since we ship python and our modules in, and from may on we can get rid of both modules and use py3-only features instead.

Creators yeah, players not really given that old build of renpy don't always work. And Linux builds aren't always made available together with the games.  
Meanwhile RenPy currently allows to play pretty much any RenPy 8.x-7.x game (not sure how that will fare with removal of `future` though).

**Comment by renpytom** [comment] 2024-11-02 03:07
Looks like this was fixed by python-future.

**Closed by renpytom** 2024-11-02 03:07 UTC
Labels: task

**Comment by lanodan** [comment] 2024-11-04 06:11
[2024-11-01 20:08:19-0700] Tom Rothamel:
>Looks like this was fixed by python-future.

How so? As marked earlier, future 1.0.0 (latest version) is broken.
