### ISSUE TITLE
Big strange memory leaks

### ISSUE THREAD

**Issue by maxlefou** [renpy/renpy#1304] opened 2017-11-26 16:03 UTC
Since the recent renpy updates, my game (a pretty basic one which always worked fine before the updates) tends to slow down and stutter hard after some time before crashing completely, sometimes giving simply a  "`MemoryError: `" in `traceback.txt` if i'm lucky. If i'm not, the pc completely freezes and crashes.

I also noticed the game launched makes the process `pythonw` taking up to 2,7Gb of memory when it happens. And it also results in a `log.txt` file of 485Mb

After some tests, i noticed the `log.txt` file gets bigger and bigger when it starts slowing down, which is why it gets so heavy. I tried to make a `tail` command to see what's in it, and [it gives this](https://pastebin.com/Q2g6Q8ZE). I'm pretty sure there's a glitch somewhere...

Am I the only one who got this? Is the problem already reported or known?

In case it helps:
Ren'Py 6.99.13.2919
Linux Manjaro, kernel 4.14.2-1-MANJARO x86_64
CPU: Intel® Core™ i3 CPU 530 @ 2.93GHz × 4
RAM: 8Gb
GPU: GeForce GTX 960/PCIe/SSE2 using nvidia official linux drivers

Note: I haven't tried on windows and i haven't tried yet on a compiled version of my game. Will update here when i'll know for these.

**Comment by renpytom** [comment] 2017-11-26 17:47
Yikes! 

Can you send me the game and the code to repeat it? It's possible that the new standard output redirection is the cause, which should be fixed in 6.99.13.1. But I want to nail this before it is a problem.

**Comment by maxlefou** [comment] 2017-11-29 15:35
mmm if you don't mind having a source archive of 140Mb (yeah it's a big project with 1080 graphics :p)

Is there any private place to send you that? I'd not like to have my game's source to be everywhere especially if it's not released yet :p

**Comment by maxlefou** [comment] 2017-11-29 16:12
ty, i'm on it

**Comment by maxlefou** [comment] 2017-12-04 14:05
so far after tests, it seems the problem only occurs when the game is launched with renpy. It doesn't seem to happen wiht the compiled version.

So, the problem isn't very dramatic. just a bit annoying for the game developpers. ^^

**Comment by XelaPy** [comment] 2017-12-07 21:13
If I may throw in my two cents:

In the latest nightlies, there seem to be two issues we've been having trouble with:

1) Using Python logging module (to write to devlog.txt file) and using the console. When using a custom logging setup in a complex game, console becomes your enemy due to the system output. It may be fixable somehow, maybe even by dropping your own logging system that you've been using for over 3 years, but this modern console stuff is all new.

I've fixed these "out of memory" issues with this:

```python
    python in _console:
        stdio_lines = []
        stderr_lines = []
        console.history = []```

Best I can tell, the numerous Text displayable fed to console from std environments are so large in size, that they crash the engine when Shift+O.

2) CDD minigames. I reckon that this has something to do with the new OpenGL performance debugging recently introduced. We even released our the latest version of the game with the "release" version of Ren'Py instead of "nightly" to be safe (for the first time ever, we should have done that at all times according to Ren'Py guidelines, but nightly has never failed us in the past ;) ). Nightly, this time, came with significant, visible decreases in CDD performance, at least in with config.developer and config.debug set to True.

**Comment by renpytom** [comment] 2017-12-08 03:16
Xela, do you have an example of the nightly performance hit. It should generally be fast unless you're leaking memory. In which case, stop leaking memory.

**Comment by XelaPy** [comment] 2017-12-08 06:57
I'll try to find out, there should not be any memory leaks, but it's always possible. 
If not, I'll try to separate the minigame from rest of the game. We are showing a VN Sprite (which is also a complex CDD) in the minigame, but if the delays (skips) are there in the nightly even without that Sprite, it's very easy to isolate the minigame CDD itself.

There is a difference between nightly and release. I am using Fraps to try getting framerate from Ren'Py, it just seems to be stuck at 60fps with nightly when minigame is running while showing different fps in the release version (different fps consistent with how many enemies are shown).

**Comment by renpytom** [comment] 2017-12-08 07:29
Xela, let's move this over to its own issue.

**Comment by maxlefou** [comment] 2017-12-08 14:51
I doubt it's that anyway, i always work with stable versions of renpy. Unless 6.99.13.2919 isn't a stable version or if this stable version has the bug?

**Comment by XelaPy** [comment] 2017-12-09 07:27
I will start a new issue if this fps thing comes back. The problem came up a number of nightlies ago. I just tried latest nightly on two different PCs, it works great everywhere.

**Comment by maxlefou** [comment] 2017-12-10 11:14
I'm now on pure arch, (kernel 4.14.4-1-ARCH) still working on the same project but the bug didn't manifested again so far. Maybe it was something related to the kernel and ren'py together?

**Comment by renpytom** [comment] 2017-12-18 06:16
I'm closing this, but please let me know if it's still there in the 6.99.14 prereleases, which will be out in a few days.

**Closed by renpytom** 2017-12-18 06:16 UTC

**Comment by maxlefou** [comment] 2017-12-22 11:55
sure will. thanks for having checked out (and corrected it? :p )
