### ISSUE TITLE
Android SDK 

### ISSUE THREAD

**Issue by flowerflow** [renpy/renpy#1819] opened 2019-05-13 04:12 UTC
As the picture shows that i have downloaded  JDK and others, but when download  andrdoid packages  ,it always connection  time out

**Comment by flowerflow** [comment] 2019-05-13 04:16
![sdk](https://user-images.githubusercontent.com/44674455/57595631-cbf70680-7578-11e9-9641-e68fe8e6d295.png)

**Comment by flowerflow** [comment] 2019-05-13 04:18
at first,  renpy tells me   the  "repositorty.cfg" does not exist, so i have creat  it and add the url.but  nothing works.please help me,thank  you   Orz
![sdk2](https://user-images.githubusercontent.com/28246959/57595647-f5b02d80-7578-11e9-840c-29be5391cc38.png)

**Comment by renpytom** [comment] 2019-05-15 05:55
I don't believe this is a problem with Ren'Py. It's more likely the problem is with your computer's internet access. Please make sure  you have a direct connection to the internet, without a firewall or censorware in the way.

**Comment by flowerflow** [comment] 2019-05-15 06:04
> I don't believe this is a problem with Ren'Py. It's more likely the problem is with your computer's internet access. Please make sure you have a direct connection to the internet, without a firewall or censorware in the way.

At first i think the problem is what you  said.So  i  have used the VPN in  Hongkong (without the VPN i even can't  download the  sdk)...But  as you see,I download the Android SDK   succeed，but  the package failed。   =  .  =.    (last  i  have  tried  in   Linux  ..still  failed......

**Comment by renpytom** [comment] 2019-05-15 06:06
Unfortunately, there's not much I can do here. The parts of the Android SDK that are failing are written by Google, not me. If they're being blocked where you are, and it's not going through your VPN, you'll have problems.

**Comment by flowerflow** [comment] 2019-05-15 06:06
> I don't believe this is a problem with Ren'Py. It's more likely the problem is with your computer's internet access. Please make sure you have a direct connection to the internet, without a firewall or censorware in the way.

Can   I  download  the  package  and  put it  in  the  directory?   Orz

**Comment by renpytom** [comment] 2019-05-15 06:07
I have no idea.

**Comment by flowerflow** [comment] 2019-05-15 06:09
> Unfortunately, there's not much I can do here. The parts of the Android SDK that are failing are written by Google, not me. If they're being blocked where you are, and it's not going through your VPN, you'll have problems.

= .=  ..thanks  for  your  reply .. That's  a little sad. Maybe i  only can  run  it  in  windows or linux.No android....
PS . your  project  (Renpy)  is  so  great!!!!  I love it!

**Comment by renpytom** [comment] 2019-05-15 06:30
Thanks for the kind words. I wish I could help more, but unfortunately, these are things you can't control. you might want to see if you can download android studio from google, and get it working - if that runs, maybe we can move things over.

**Comment by renpytom** [comment] 2019-05-29 02:24
Closing this, as I don't see anything more I can do.

**Closed by renpytom** 2019-05-29 02:24 UTC

**Comment by flowerflow** [comment] 2019-05-29 08:10
OK~~
