### ISSUE TITLE
renpy.show_layer_at() breaks all MoveTransition()

### ISSUE THREAD

**Issue by BattleProgrammer-san** [renpy/renpy#2821] opened 2021-05-23 16:06 UTC
**Description**:
As soon as renpy.show_layer_at() is called for the master, every instance of move breaks. So move, moveinleft etc. all instantly jump to the target destination, but the text still waits for the given time.

**Expectation**: 
The images still move as usual, smoothly, no jumps.

**Result**:
The image instantly jumps to the target location, while the text waits for the time the animation is supposed to run.

**Example and steps to reproduce**:
```
transform pan_to_left:
  zoom 1.1
  ypos -50
  xpos 0

label test:

  #default scene
  scene black

  #the following movein works as intended
  show test_image at center with moveinleft

  #pans the camera to the left, bg and sprites included (master layer)
  $ renpy.show_layer_at(pan_to_left, reset=False)
  #the above line causes the bug - no move will work until another scene change

  #small break so we can see things are happening
  "..."
  
  #attempt at another move - but the image just jumps to the target immediatly
  hide test_image with moveoutright

  "..."

  return
```

**Comment by Gouvernathor** [comment] 2021-12-27 16:03
Most likely duplicate of #2995, and fixed the same way.

**Comment by Andykl** [comment] 2021-12-27 18:23
Agree. @BattleProgrammer-san, if the issue is not fixed by this, feel free to reopen.

**Closed by Andykl** 2021-12-27 18:23 UTC
