### ISSUE TITLE
Can't start renpy.sh - Permission denied

### ISSUE THREAD

**Issue by cawa-93** [renpy/renpy#5098] opened 2023-11-05 14:43 UTC
I can't run a script from the command line to investigate the CLI workflow. No matter what I do, I always get the same error:

```bash
$ bash ./renpy.sh --help
./renpy.sh: line 63: /c/Users/kozac/Downloads/renpy-8.1.3-sdk/lib/py3-linux-x86_64/renpy: cannot execute binary file: Exec format error
./renpy.sh: line 63: exec: /c/Users/kozac/Downloads/renpy-8.1.3-sdk/lib/py3-linux-x86_64/renpy: cannot execute: Permission denied
```

I tried changing `renpy.sh ` and `lib/py3-linux-x86_64/renpy` files permissions and running the command as administrator, but it didn't have any effect.

I don't understand in which direction to investigate the problem. 

renpy version 8.1.3

**Comment by mal** [comment] 2023-11-05 17:31
You file path makes me suspect that you extracted Ren'Py on a Windows machine before trying to run it under WSL (Windows Subsystem for Linux). Doing so will mean that some file attributes necessary for running under Linux will have been lost - such as the executable bit you second error line is complaining about.

I'd suggest extracting and running using the same system, be it either Windows or Linux. Also while it may be possible to run Ren'Py under WSL, I don't believe it's considered a support platform.

**Comment by cawa-93** [comment] 2023-11-05 18:32
@mal Sorry for the poor explanation of the problem.

I'm using Windows. I downloaded and unzipped the `SDK 7z.exe`. I'm trying to run the script using Git Bash for Windows and not WSL. 

In fact, I am not sure if I am using the correct entry point. I tried running 
```
/renpy-8.1.3-sdk/renpy.exe --help
```
and
```
/renpy-8.1.3-sdk/lib/py3-windows-x86_64/renpy.exe --help
```

This did not show any errors or help information. 

I also did not find the relevant section in the documentation. What I want to do is run linter, update translations or compile distributions from the command line.

**Comment by mal** [comment] 2023-11-05 18:43
The correct entry point on Windows is `renpy-8.1.3-sdk/renpy.exe`. Which version of Windows are you running, and is it on 32-bit (x86) or 64-bit (x86_64) architecture?

**Comment by cawa-93** [comment] 2023-11-05 21:26
Windows 11 Pro 22H2. 64bit. GUI work as expected

**Comment by mal** [comment] 2023-11-05 21:47
Thanks, given that normal operation seems fine, and that we already have a very similar issue around CLI use, I'm going to close this as a duplicate. You can subscribe to the linked issue to be notified when progress is made in that area.

---

**Thread Summary**

> What I want to do is run linter, update translations or compile distributions from the command line [on Windows].

Ultimately this seems to be a duplicate of #4257. The strange behaviour described in OP is the result of attempting to run the Linux binary on a Windows system in an attempt to trigger specific Launcher tasks from the command line.

**Closed by mal** 2023-11-05 21:47 UTC
