### ISSUE TITLE
config.screen_width and config.screen_height not working as before

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#4276] opened 2023-01-24 16:32 UTC
Hello,

according to Ren'Py documentation, config.screen_height and config.screen_width should be two simple integers, and so it was until at least Ren'Py version 7.4.11. However, during an update to Ren'Py 8.0.3, I noticed that this variables no longer work as before, giving instead results like "(0, 1920)" or "(0, 1080)". Using print in the console makes the new behaviour evident. Is this change intended, or is it a bug?

**Comment by renpytom** [comment] 2023-01-24 19:56
Can you try this in the tutorial? I'm unable to repeat this.

**Comment by danac78** [comment] 2023-01-25 16:46
I can confirm on a game built on 8.0.2 (now on 8.0.3) that it will print it as integers.

**Comment by shawna-p** [comment] 2023-01-25 17:39
It's because you're using `print config.screen_width` not the correct `print(config.screen_width)`

**Comment by danac78** [comment] 2023-01-25 17:49
@Dumcem The reason you see different results for 7.5.3 and 8.0.3, 7.5.3 uses Python 2.7. 8+ uses Python 3.9, which uses print() for the same result you got in 7.5.3 and earlier.

**Comment by Dumcem** [comment] 2023-01-25 18:09
Ok, I was trying to figure out why jsfehler's renpy-encyclopaedia was having problems getting the correct screen size in 8.0.3. The problem wasn't what I thought; instead, it was in the expression `config.screen_width / 2`, which gives the value 640.0 instead of 640. So, using `int(config.screen_width / 2)` seems to solve the problem.

**Comment by danac78** [comment] 2023-01-25 18:12
@Dumcem Someone could correct me if I am wrong or misremembering. The reason is that when / in 8.0.3 (Python 3.9), it returns a float instead of an integer when you perform something like that.

**Comment by Dumcem** [comment] 2023-01-25 18:20
@danac78 Yes, it's like you said. I'm opening a report on jsfehler's renpy-encyclopaedia.
Thank you very much :)

**Comment by renpytom** [comment] 2023-01-25 19:49
I think we can close this. Thank you, @danac78 , for figuring this one out.

**Closed by renpytom** 2023-01-25 19:49 UTC
