### ISSUE TITLE
if the "w" text tag is given an argument in "what_suffix" the wait doesn't automatically end.

### ISSUE THREAD

**Issue by Tapirismus** [renpy/renpy#2749] opened 2021-04-02 20:07 UTC
If I use the "w" text tag with a given argument in "what_suffix", e.g. ( what_suffix= "{{w=1.0} hello)" ) , it treats the "w" as if it has no arguments, meaning I always have to click to continue and the wait never automatically ends.
Thank you in advance

**Comment by renpytom** [comment] 2021-04-02 22:30
I'm not able to repeat this:

```
define _confirm_quit = False
define e = Character("Eileen", image="eileen", what_suffix="{w=1.0} test")

label main_menu:
    return

label start:

    e "test"

    return
```

Works fine for me.

**Comment by renpytom** [comment] 2021-05-19 03:31
Closing, since I can't reproduce this. Feel free to re-open it.

**Closed by renpytom** 2021-05-19 03:31 UTC
Labels: can't reproduce
