### ISSUE TITLE
Setting config.has_voice = True causes voice lines to cut off almost immediately

### ISSUE THREAD

**Issue by VmmersionStudio** [renpy/renpy#5829] opened 2024-10-06 03:06 UTC
I've used both Renpy 8.3.0 and 8.3.2.

Project has config.has_voice = False by default, which we didn't change at first, but we did add multiple play voice statements to our script. The voices actually do work, but there is no mixer for voices. When setting config.has_voice = True in options.rpy, the mixer appears, but now all of our voice lines cut out after like half a second of playing.

**Comment by renpytom** [comment] 2024-10-06 03:12
Is this your project, or a mod to another game?

**Comment by renpytom** [comment] 2024-10-12 15:13
Closing this for lack of information.

**Comment by VmmersionStudio** [comment] 2024-10-16 02:00
Sorry for the late response, this is my project.

**Comment by renpytom** [comment] 2024-10-16 02:04
Okay, can you pt

**Comment by VmmersionStudio** [comment] 2024-10-16 02:21
I was able to reproduce it with a fresh project in Ren'Py 8.3.2 where I add an audio file (in my case, an OGG file), and add a `play voice "DW1.ogg` line in front of some dialogue. When I try this, it didn't play anything (could be coincidental). I then go into options.rpy and change `config.has_voice = True` to `config.has_voice = False` and then start the game again and it plays fully.
[test.zip](https://github.com/user-attachments/files/17388336/test.zip)

**Comment by VmmersionStudio** [comment] 2024-10-16 02:32
I also just replicated it on a fresh computer where I download the latest version from the website, created a new project, and repeated the same steps above (I did an mp3 this time).

**Comment by renpytom** [comment] 2024-10-16 03:07
So, the issue is that you're using ``play voice`` and should be using ``voice``. The former just plays audio on a channel named 'voice', and the latter is how to invoke Ren'Py voicing system.

**Closed** 2024-10-18 02:20 UTC
