### ISSUE TITLE
Is there a way to enable / disable a shader?

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#3732] opened 2022-07-02 22:19 UTC
_(not for me, for a friend of mine)_

they want to make a button that if a persistent if True, it renders the whole screen with a shader, and without if the persistent is False.

that was the code that i _shamelessly stole from someone_
```
python early hide:
    from functools import partial

    class THING(object):
        def __init__(self, func):
            self.func = func

        def __get__(self, obj, objtype):
            return partial(self.__call__, obj)

        def __call__(self, *args, **kwargs):
            rv = self.func(*args, **kwargs)

            if persistent.using_shader:
                rv.mesh = True
                rv.add_shader("FILTERNAME")

            return rv
    
    renpy.display.render.render_screen = THING(renpy.display.render.render_screen)

default persistent.using_shader = False
```
but the only thing that it does is making the whole screen pitch black.

any ideas?

**Comment by renpytom** [comment] 2022-07-03 01:08
This isn't close to correct. 

You probably want to create a Transform that sets up the shader, and then use the camera statement to apply it to all layers.

**Comment by Elckarow** [comment] 2022-07-03 09:42
that was the first thing i thought of doing, but all it did is either do nothing or pitch black screen, same as above - which is why i tried changing the way the screen itself is rendered.

**Comment by renpytom** [comment] 2022-07-03 15:04
Here's an example of it working. 

```renpy

init python:
    renpy.register_shader("example",
        fragment_1000="""
gl_FragColor.rgba = gl_FragColor.bgra;
""")

transform example:
    mesh True # Optional for this shader.
    shader "example"

label start:

    camera at example

    scene bg washington

    "..."

    return
```

Beyond that, the problem is likely in your shader itself.

**Comment by Elckarow** [comment] 2022-07-03 18:08
what they want to do is have a button in the settings that if clicked on, it renders **everything** with the shader.
say the shader makes the screen only use white and black, then everything will be in black and white.

it's like chosing between window mode and full screen mode, but with a shader.

and the shader is working fine, i tested it with the regular `camera at example`.

**Comment by renpytom** [comment] 2022-07-03 19:22
A CDD is the way to go for this:

```renpy
init python:
    renpy.register_shader("example",
        fragment_1000="""
gl_FragColor.rgba = gl_FragColor.bgra;
""")

default persistent.shader = True

init python:

    class ShaderMagic(renpy.Displayable):

        def __init__(self, child):
            super(renpy.Displayable, self).__init__()
            self.child = child

        def visit(self):
            return [ self.child ]

        def render(self, width, height, st, at):
            rv = renpy.Render(width, height)

            cr = renpy.render(self.child, width, height, st, at)
            rv.blit(cr, (0, 0))

            if persistent.shader:
                rv.add_shader("example")

            return rv

        def event(self, ev, x, y, st):
            return self.child.event(ev, x, y, st)

screen test():

    add "eileen happy"
    textbutton "Toggle":
        action ToggleField(persistent, "shader")

label start:

    camera master at ShaderMagic
    camera screens at ShaderMagic

    scene bg washington
    show screen test

    "..."

    return
```

**Comment by Elckarow** [comment] 2022-07-03 20:11
aight it's working, thanks 👍 👍

**Comment by renpytom** [comment] 2022-07-04 15:24
Look good, closing this issue.

**Closed by renpytom** 2022-07-04 15:24 UTC
