### ISSUE TITLE
Audio fadeout broken in Firefox

### ISSUE THREAD

**Issue by neobenedict** [renpy/renpy#3334] opened 2022-03-16 00:49 UTC
https://github.com/renpy/renpy/blob/master/renpy/common/_audio.js#L255

linearRampToValueAtTime works in Chrome but in Firefox (most recent mobile version & older desktop version 87.0) it breaks, setting the channel volume to 0.00 permanently without any sort of ramp.

My workaround is to just pass a curve to setValueAtTime instead, ~~then remember to set the channel volume back~~ nope this is another bug in firefox, see below. It may not be best but it's better than nothing.

I will let you decide on a fix since I don't really know what I'm doing here or why this api doesn't work in firefox in the first place. The bug may be much simpler and this workaround isn't needed.

**Comment by mal** [comment] 2022-03-16 01:42
Relevant FF bug reports:
https://bugzilla.mozilla.org/show_bug.cgi?id=1171438 - Open for 7 years
https://bugzilla.mozilla.org/show_bug.cgi?id=1567777 - Marked duplicate of ^

**Comment by neobenedict** [comment] 2022-03-16 02:01
https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/exponentialRampToValueAtTime#browser_compatibility

**Comment by neobenedict** [comment] 2022-03-17 23:03
Okay this is more broken than I thought, a lot of the file needs chaning, `c.fade_volume.gain.value =` does nothing in Firefox either (replace with `c.fade_volume.gain.setValueAtTime(1.0, context.currentTime);`)

Somewhat more functional script but still broken https://gist.github.com/neobenedict/ae22958a331fb88a571e037d5c25d589

**Closed** 2022-04-17 02:40 UTC
