### ISSUE TITLE
Display glitch on certain devices

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4343] opened 2023-02-11 14:52 UTC
Greetings,

Several of our players have reported a visual glitch issue when they launch our game. See below.

![unnamed](https://user-images.githubusercontent.com/34620611/218264386-781d825d-61f7-4087-bdf6-01e48bb7411b.png)
![unnamed2](https://user-images.githubusercontent.com/34620611/218264391-8651368e-71f9-4796-9356-743670b94ca2.png)

One of them told us they managed to find a workaround:
"I had to disable Ren'Py's OpenGL support, which is done by holding down shift while starting the game. I was then able to force the game to use a different software renderer from the available options and now the backgrounds and CGs look as they should both in-game and in the gallery."

Just figured it may be worth reporting.

**Comment by mal** [comment] 2023-02-11 15:05
Likely duplicate of https://github.com/renpy/renpy/issues/4245, the tl;dr of which is that it seems likely to be down to using very old drivers and graphics hardware.

**Closed** 2023-02-11 16:43 UTC
