### ISSUE TITLE
Tag (ex. {i}, {b}, etc) will turn everything following it into text until it finds a closing tag 

### ISSUE THREAD

**Issue by CptHappyBoy** [renpy/renpy#4688] opened 2023-06-03 16:17 UTC
Hello! 
If a tag (ex. {i}, {b}, etc) is inside any string, everything following it will be converted to text until the end tag is found.

This is not affecting the game and the code compiles as expected, but code interpritated as regular text. 
Can someone please take a look? 

![brackets broken](https://github.com/renpy/renpy/assets/135448816/ec921110-a127-4045-a04b-093f15d1bb14)

**Comment by renpytom** [comment] 2023-06-03 16:42
This looks like a duplicate of LuqueDaniel/vscode-language-renpy#328, so it's best addressed there.

**Closed by renpytom** 2023-06-03 16:42 UTC

**Comment by duckdoom4** [comment] 2023-06-03 21:31
@renpytom Yeah, we just converted our pre-release into a new public release. We've had this version in pre-release for quite a while and think it's stable enough for release. Though ofcourse we do expect some unreported bugs to pop-up, so feel free to keep sending everyone our way. Apologies for the extra management work in advance :)
