### ISSUE TITLE
Samsung S6, Factory Reset, Fully System Updated, Android 7.0 - Constant Crashing with any Ren'py App.

### ISSUE THREAD

**Issue by henvu50** [renpy/renpy#4776] opened 2023-06-24 03:24 UTC
_EDIT: I just learned about the logcat, they're attached at the end of my post, for each unique crash scenario._
Samsung S6, Factory Reset, Fully System Updated, Android 7.0 
Problem: **Constant Crashing with any Ren'py App; if left at main menu. If started a new game, quit menu gets invoked every time for unknown reason, usually up to the two minute and 30 second mark, then ren'py app remains unresponsive. Fully tested with many different APK's, including The Question & Ren'py launcher tutorial.**
Notes: Other games, like Unreal Engine 5 demo APK, work fine on the phone; fully tested for 30 minutes plus, so I know the phone isn't broken.
NOTE: I'm in no rush to fix this, I'm currently testing my game on Android 9.0 phone, so you can really take your time and decide if this is worth fixing or not.
For complete details: https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=66793 _(It's a complicated problem unfortunately, so don't visit this forum post yet., before reading the following...)_.

See, I don't know if this issue is worth fixing, because only **3%** of users worldwide use **Android 7.0**, and only **1.8%** of users worldwide use **Android 5.01** (source: https://www.androidauthority.com/android-13-version-distribution-may-2023-3332337/)

I wonder if the minimum Android version that Ren'py supports should be increase to Android 9.0+, then this issue won't even have to be resolved, lol.

If you guys truly want to maintain a compatibility with Android 5.01+, how would we proceed? I'm willing to go above and beyond, attempting advanced level stuff to help anyway I can, to fix this problem. 

I have a history of successfully finding bugs in Ren'py to fix, so please trust I'm not wasting your time; and in no way do I want to waste your time.

Here is the exact problem, in case you don't want to read the wall of text in the forum post:

**Problem**: Any Ren'py app I run on my phone randomly crashes within two minutes and forty seconds. This means I run the Ren'py application on my android phone, then I let it sit at the main menu; I don't press or click anything, the Ren'py app just stays open in fullscreen, but then it'll randomly exit / crash anywhere from a few seconds in, up to two minutes and forty seconds, every time. It just goes back to the home screen. The app remains open, but if I try to go back into it, it shows Ren'py loading screen or the app restarts.  

Upon further investigation, if I click Start, making a new game, within that two minute and forty second duration, something invokes the quit menu; yes, it's not supposed to do that on mobile; this happens on ANY ren'py APK, that's the crazy thing. I 'm not even touching the screen, I just start new game, tap forward a few times, then let it sit, then all of a sudden the quite menu randomly gets invoked, then unresponsive. If I tab out and back in, it usually restarts and goes to main menu or gets stuck at the default ren'py mobile loading screen forever.

If you really want to fix this problem, I'm willing to go AS FAR AS YOU want me to go to fix this, giving you as much precise detail as possible. I would just need a little help and guidance. I'm even willing to ship you the phone if it makes things easier, but let's leave that as a last resort.

But like I said above, is it even worth fixing if the android 7.0 user base is only 3% worldwide? IMO no, lol.

**UPDATE: 6/24/2023 - 12:22AM PST**
I compiled a new Ren'py application. Its package-name is: **bob.fox.trolly8**, that shoud make finding it in the log cat super easy.

1st logcat: [logcat.txt](https://github.com/renpy/renpy/files/11855898/logcat.txt) - I launched the app in phone at 12:33AM, then I left it at the main menu, didn't touch anything, and it randomly exits out at 12:34AM. 

2nd logcat: [logcat2.txt](https://github.com/renpy/renpy/files/11855915/logcat2.txt) - I launched the ren'py app in my phone, then it closes very quickly, only being at the main menu for a very short duration. 

3rd logcat: [logcat3.txt](https://github.com/renpy/renpy/files/11855934/logcat3.txt) - Launched app from my phone, but this time I clicked START at the main menu. Looks like Eileen images won't even show; i get red warnings on the top left, but that's beside the point.  After clicking start, I just let it sit there, and when the quit menu gets randomly invoked; and the app becomes responsive, I have that whole duration logged in the logcat. I have screenshots from the phone to show I'm not crazy:

So after letting it sit there, the quit menu gets invoked, but it goes unresponsive.
![2](https://github.com/renpy/renpy/assets/82792098/2e3f53eb-0d58-4ddf-939f-7102167cbd6f)

Still unresponsive and Android notices too:
![3](https://github.com/renpy/renpy/assets/82792098/63eaae5f-ae42-4ef8-aaf6-eacb9f73a999)

At this point, if I try to tap back in, it just shows black screen.
![4](https://github.com/renpy/renpy/assets/82792098/92f79528-47f7-4285-ab33-76e5910f9591)

Phone info: 
![5](https://github.com/renpy/renpy/assets/82792098/9d813deb-259e-4dce-89fb-9c0af5781a27)

I hope this helps. Tell me what you need, anything I can do to save time.

I can actually try and save a video of the problem happening in real time too, so let me know.

**Comment by renpytom** [comment] 2023-06-24 13:07
I'm not actually seeing a crash in those logcats. I'm seeing:

```
06-24 00:34:24.948 17168 17168 V SDL     : onConfigurationChanged()
06-24 00:34:25.085 17168 17168 V SDL     : onPause()
06-24 00:34:25.086 17168 17168 V SDL     : nativePause()
06-24 00:34:25.095 17168 17168 D SensorManager: unregisterListener :: 0, MPU6500 Acceleration Sensor,  
06-24 00:34:25.102 17168 17168 V SDL     : onStop()
06-24 00:34:25.102 17168 17168 V python  : onDestroy()
06-24 00:34:25.102 17168 17168 V SDL     : onDestroy()
```

I don't know what is causing the onConfigurationChanged, but the rest of it is a normal OS-requested shutdown. 

I'm looking at this in other Android 7 devices. Ren'Py has been running fine in an emulator running Android 7 for me, so far. I need to see if I can get my android tablet from that era to boot, to try it there. 

I've had recent feedback of Ren'Py running on other similarly-aged devices, so I'm unlikely to drop support based on one device not working. I may add some logging to onConfigurationChanged.

**Comment by henvu50** [comment] 2023-06-24 21:03
I understand.  Just to shed some light.  This phone used to run Ren'py games just fine, but after I did a factory reset, followed by a system update, this problem showed up.  I'm guessing maybe the system update, updated the Android version from 5.0.1 to 7.0. That's the only thing I can think of.

I also don't have any problems running my game in an Android 7.0 emulation.

This was my primary phone for testing my Ren'py game. Since it can no longer serve that purpose, **do you want the phone**? I can ship it to you, if you want. If not, np.  It will always be here if you ever want to investigate this issue; _for example, in case this issue comes up again in the way future._ 

Can you tell me what errors you look for in the logcat, that signifies a crash? Just so I know for the future?  I would love to be able to learn enough about Ren'py Android Logcat inspection, so I can give better information, in case I find a more serious bug on Android in the future.  If not, and you're busy, np.  Take care!

**Comment by henvu50** [comment] 2023-06-24 21:45
I had one more question if you don't mind. What mobile phone do you use for testing?

**Comment by renpytom** [comment] 2023-06-25 00:33
If you want to send me the phone, I'll take it and try to figure out what's wrong. But it's an old phone, so it's possible it's something phone specific. 

I use a bunch of them. My pixel 7 is the most common, but I also test on a pixel 2xl, a s10e, and a few tablets of various vintages. (I  find I have to test separately on Samsung devices and pixels.)

**Comment by renpytom** [comment] 2023-06-29 02:28
Closing this as can't reproduce, since I tried on multiple devices and couldn't repeat it.

**Closed** 2023-07-06 04:36 UTC
Labels: can't reproduce, platform-android
