### ISSUE TITLE
noloop stops audio after rollback

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#4179] opened 2022-12-23 23:50 UTC
Using `noloop` causes audio files to stop playing after rollback.

```
label start:
    "1"
    play music "audio/file.mp3" noloop
    "2"
    "3"
    $ renpy.rollback()
```

Checked on the last Nightly build

**Comment by renpytom** [comment] 2022-12-24 20:35
This is intended behavior. Noloop is intended for sound effects, not music. And I think it makes sense to cancel the playing sound effects if the player rolls back

**Comment by via-my** [comment] 2022-12-25 04:16
But what about sounds like fanfare? Such sound should not loop and should not stop after an accident rollback.

**Comment by renpytom** [comment] 2022-12-25 18:13
It should stop after a rollback. The current behavior for non-looping sounds is correct.

**Comment by via-my** [comment] 2022-12-27 08:43
I mean what if file is 15 or more seconds long? What about adding one small keyword?

`
play sound “...” dontstopplayingonrollback
`
😵‍💫
Or `ignore_rollback`

**Comment by renpytom** [comment] 2023-01-17 07:06
I don't see any straightforward way to implement this, and I don't see an issue with the current behavior, given rollback's equivalence to a save and a load. I'm closing this out.

**Closed by renpytom** 2023-01-17 07:06 UTC
