### ISSUE TITLE
Preferences audio_when_minimized does not behave as expected

### ISSUE THREAD

**Issue by Aristarhys** [renpy/renpy#3661] opened 2022-06-14 19:33 UTC
Hi, sadly i can't achieve correct behavior for muting audio on "minimize/iconify" on Ubuntu 18.04.6 LTS, Ren'Py version 7.4.11.2266

My `options.rpy` contain [simple definition](https://www.renpy.org/dev-doc/html/preferences.html#var-preferences.audio_when_minimized) (it's even unnecessary as it's should be `False` by default)

```
default preferences.afm_time = 15

default preferences.audio_when_minimized = False
default preferences.wait_voice = True
```

Switching to other window or minimizing game window does not have effect no matter what and it's true for full screen and windowed mode.

I see PR which requested such feature - https://github.com/renpy/renpy/issues/2645

I see properly made PR which implemented it - https://github.com/renpy/renpy/pull/3431

By all means it should really mute everything, unless

https://github.com/renpy/renpy/pull/3431/files#diff-6f104b68cba86cdde2dd3341efbdbe8ba7409bcd96185ee10285022bebd3b94fR4187

[pygame.display.get_active](https://www.pygame.org/docs/ref/display.html#pygame.display.get_active) return `True` all the time.

As stated

```
This will return False if the display Surface has been iconified or minimized (either via pygame.display.iconify() or via an OS specific method such as the minimize-icon available on most desktops).

The method can also return False for other reasons without the application being explicitly iconified or minimized by the user. A notable example being if the user has multiple virtual desktops and the display Surface is not on the active virtual desktop.
```

Pretty sure [renpy.audio.audio.pause_all](https://github.com/jsakaa/renpy/blob/b5f55c0fdd1fd397ff3d373e0f16663903ea61c0/renpy/audio/audio.py#L1238) can't be broken to be a reason for such behavior.

So my wild guess what PR introduced setting is fine, but pygame don't register minimize/window switch events properly.

**Comment by Booplicate** [comment] 2022-06-14 20:05
I've never had any luck with `pygame.display.get_active` in my projects. When I needed to check if the window has focus, I had to use `ACTIVEEVENT` like this:
```py
if event.type == pygame.ACTIVEEVENT and event.state == 2:
    game_focused = bool(ev.gain)
```

**Comment by renpytom** [comment] 2022-06-15 01:51
I'm unable to repeat this. I've tried this on Ubuntu 22.04 (Gnome) and Windows 10, and it worked in both places. I'd think it's possible that there are configurations of Linux that might not get this right, but that's likely to be a configuration problem. At least on my computer, pygame.display.get_active() works fine.

**Comment by Aristarhys** [comment] 2022-06-15 15:56
@renpytom it's honor to receive your response and thanks for all hard work on this engine.
I'm not sure if there is some special policy about proposal of changes, but i plan to take look at the issue myself as soon as it's possible. I understand what my system outdated and can be issue itself.

**Comment by renpytom** [comment] 2022-06-15 17:27
Sure. 

I think in this case, I'm probably not going to accept a change for this. We're getting the maximized/minimized information out of SDL, so if the problem is going to be fixed, it should be fixed at the SDL level.

**Comment by renpytom** [comment] 2022-06-19 01:49
This appears to be working the way it should. config.audio_when_minimized works when the window is minimized, not when it's simply switched away from.

**Closed by renpytom** 2022-06-19 01:49 UTC

**Comment by Aristarhys** [comment] 2022-06-19 12:56
@loafylemon @renpytom yes, sorry for the mess, not a bug.
