### ISSUE TITLE
Custom mouse cursors not rendered correctly [7.4.0]

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#2572] opened 2021-01-05 07:36 UTC
Since updating to 7.4.0 (stable) and also testing 7.4.1 (nightly) my custom mouse cursors (.png and .ico) are not rendered correctly.

Issue: some semi transparent pixels are displayed as non-transparent (0% alpha), which causes the cursor to look annoying. The 100% alpha pixels are rendered correctly though.

I use a lot of custom cursors and before the update everything worked fine. I read about changes to the rendering engine, so there might be an issue.

From the changelog: "Defining a mouse cursor using config.mouse now uses SDL2's color cursor API, which generally results in hardware acceleration and reduced mouse movement lag."

My system: Ubuntu 20.04 (64-bit)

**Comment by renpytom** [comment] 2021-01-06 07:44
Hm... 

I don't believe .ico files are supported in Ren'Py, so we can probably dispense with those. 

My guess is you might not have the libxcursor1 package installed. That library is needed for cursors with proper transparency, so if it's not there, you'll have problems like the ones you describe. I was able to check for it loading with:
```
strace lib/linux-x86_64/python renpy.py  ../tests/transcursor/ 2>&1 | grep Xcursor
```
from the command line. Beyond that, if you have a png file with a problem, I can look at it and see if it works here. I develop on Ubuntu 20.04, so I can confirm it's basically working on this platform.

**Comment by m-from-space** [comment] 2021-01-06 12:42
Hey renpytom,

thanks for your reply. I have libcursorx1 installed (1.2.0-2).

I only use .png icons, which worked fine in 7.3.5. Since I encountered the problem in 7.4.0 I wanted to test if an .ico file would fix the problem. It didn't, but worked fine nevertheless. I just loaded my program back in 7.3.5 on the same system and the mouse point problem doesn't occur. So I don't think it is because my system is missing something (and maybe it also shouldn't be).

Here is a screenshot of the differences: 
![renpy_cursor](https://user-images.githubusercontent.com/76992439/103769595-da831300-5024-11eb-9f3f-aab29bb2eb56.png)

**Comment by renpytom** [comment] 2021-01-06 14:58
Hm... At least for me, it's working fine. The accelerated cursor doesn't show up in screenshots, so here's a photo of my screen:

![image](https://user-images.githubusercontent.com/379804/103782380-638a5200-5005-11eb-9a03-31c6617c3803.png)

I asked about strace because if Xcursor wasn't available, SDL2 would use an older path that could cause artifacts like what you're seeing. 

I'm not going to revert to something like the 7.3.5 way of doing custom cursors, which was to draw them using OpenGL. There were too many cases where that would lead to a 2-3 frame latency, which was pretty much unacceptable. So basically, I need to figure out what's wrong with your Linux box, including what desktop environment you're using.

**Comment by m-from-space** [comment] 2021-01-06 18:14
So to start with strace: I actually never used this command myself, so I have no experience regarding it. Your commandline run from the renpy SDK folder doesn't output anything, it actually just stops and renpy doesn't even start. But I don't know what the /tests/transcursor arguments is doing there, sorry.

I use the standard Gnome environment that ships with Ubuntu 20.04.

How can I help to figure out what's going on here?

**Comment by renpytom** [comment] 2021-01-07 00:21
Oh, sorry - the thing I got wrong was that 

strace lib/linux-x86_64/python renpy.py  ../tests/transcursor/ 2>&1 | grep Xcursor

should be

strace lib/linux-x86_64/python renpy.py path/to/your/game 2>&1 | grep Xcursor

**Comment by m-from-space** [comment] 2021-01-07 09:19
So the output is the following:

openat(AT_FDCWD, "/home/USER/Programs/renpy-7.4.0-sdk/lib/linux-x86_64/libXcursor.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libXcursor.so.1", O_RDONLY|O_CLOEXEC) = 17
openat(AT_FDCWD, "/home/USER/Programs/renpy-7.4.0-sdk/lib/linux-x86_64/libXcursor.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libXcursor.so.1", O_RDONLY|O_CLOEXEC) = 17

There is no libXcursor.so.1 in the directory, it's no wonder that it cannot open it. I don't know what to make of it? Should renpy ship the libXcursor file? As I said it is installed on my system, I also installed the libxcursor-dev files just to make sure. ^^

**Comment by renpytom** [comment] 2021-01-07 14:20
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libXcursor.so.1", O_RDONLY|O_CLOEXEC) = 17

Since you're getting a number there, it's opening libXcursor.so.1, which means that Ren'Py should be using Xcursor. I'll be honest, at this point I'm thinking there might be some issue with the hardware or software of your system, that's causing it to not work properly.

What sort of GPU do you have?

**Comment by m-from-space** [comment] 2021-01-09 19:46
I am on Gnome, my GPU is that of a Radeon HD 7950, I don't encounter any other issues to be honest. Like my normal mouse cursors work fine.

I don't use any proprietary drivers either.

**Comment by m-from-space** [comment] 2021-01-10 10:59
Update: Just tested my project built for "PC (Windows + Linux)"

1. Same problem on Ubuntu 20.04 live USB (!) startup system
2. No cursor problems within the Windows 10 system on the same machine

**Comment by renpytom** [comment] 2021-05-19 03:45
Closing this, as I don't know what it could be. There is MouseDisplayable,  now, if you want to try using that.

**Closed by renpytom** 2021-05-19 03:45 UTC
