### ISSUE TITLE
What is the best way to handle animation inside a shader?

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#3041] opened 2021-09-16 04:44 UTC
Given the default new shader on shadertoy.com:

```
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    // Normalized pixel coordinates (from 0 to 1)
    vec2 uv = fragCoord/iResolution.xy;

    // Time varying pixel color
    vec3 col = 0.5 + 0.5*cos(iTime+uv.xyx+vec3(0,2,4));

    // Output to screen
    fragColor = vec4(col,1.0);
}
```

Which is then adapted for Ren'Py: 

```
init python:

    renpy.register_shader("example.new", variables="""
        uniform vec2 u_model_size;
        uniform float u_time;
    """, fragment_300="""
        // Normalized pixel coordinates (from 0 to 1)
        vec2 uv = gl_FragCoord.xy/u_model_size.xy;

        // Time varying pixel color
        vec3 col = 0.5 + 0.5*cos(u_time+uv.xyx+vec3(0,2,4));

        // Output to screen
        gl_FragColor = vec4(col,1.0);
    """,
    )

transform new_shader:  
    shader "example.new"

```

The frame rate on the shader will be low. When the following is added:

```
    def redraw_function(t, st, at):
        return 0

transform new_shader:  
    shader "example.new"
    function redraw_function
```

The frame rate matches shadertoy.

Is this the correct way to handle immediate redraws?

**Comment by renpytom** [comment] 2021-09-16 20:20
This works, as would, probably:

```
pause 0
repeat
```

**Comment by renpytom** [comment] 2021-09-17 04:57
Actually, that didn't work - but I've gone ahead and special cased it, so that it will work from now on. What I'd recommend for this as of the 2021-09-17 nightly is:

```renpy
transform new_shader:  
    shader "example.new"
    pause 0
    repeat
```

**Comment by jsfehler** [comment] 2021-09-17 23:40
That worked on the nightly for me. 

I've seen another side effect which occurs in both 7.4.9 prerelease and 09/17 nightly, so unrelated to your change:

When one shader has `pause 0 repeat` (or a redraw function) all the shaders applied to images are redrawn as well. eg:

```
    show chara1 at amazing_shader_tf
    show chara2 at stupendous_shader_tf

    transform amazing_shader_tf:  
      shader "example.new"
      pause 0
      repeat

  transform stupendous_shader_tf:
    shader "example.another"
```

Is this the intended behaviour? If so, maybe it makes more sense for transforms with shaders to implicitly redraw, unless the transform is a transition? Or maybe allow inline syntax like:
```
 show chara2 shader "example.new"
```

to implitly redraw and avoid writing similar transforms for every custom shader.

**Comment by Gouvernathor** [comment] 2021-09-18 00:25
The repeat instruction makes the whole block repeat, so the `shader` atl instruction is re-read at each loop.
Maybe the effect would be different if you put the pause and the repeat inside a `block:` block, with the shader property before it.

As for the automatic redraw, given that all transforms have shaders like renpy.texture enabled by default, and most creator-defined shaders are not animated, it would probably waste a lot of processing power to enable quick redraw by default.

**Comment by renpytom** [comment] 2021-09-18 01:02
This is intended behavior, and to understand it requires an understanding of where shaders fit into the drawing process. There are two passes 

The first is that the relatively slow Python code builds up a tree of Renders, one for each Displayable that's going to be drawn to the screen. These Renders are only re-created when the displayable underlying the screen changes. Ren'Py then determines when to display a frame, with frame display occuring at least 5 times a second, and going up to the FPS of the player's display/

When it's time to display a game, Ren'Py walks the tree of of displayables, and uses this walk to create draw operations to send to the GPU for the operation. The draw operations consist of a model (a mesh, a set of textures, and a set of default shaders, uniforms, and properties), and additional uniforms, shaders, and properties. The GPU then performs the draw operation. 

It's important to realize that every shader is run for every frame that Ren'Py chooses to display. That's fundamental to the shader model - there isn't a way to display a frame that doesn't involve running every shader. So basically, what's happening is that with 

```
pause 0
repeat
```

You're maxing out Ren'Py's framerate, and when doing so, every shader runs on every frame, which explains why other shaders are updating. If you need more precise control over frames, use your own uniform, not ``u_time``.

**Comment by jsfehler** [comment] 2021-09-19 19:56
@renpytom Thanks for the explanation. It also explains why:
```
    shader "example.new"
    u_custom_time 0.0
    linear 60.0 u_custom_time 100.0
    repeat
```

has a similar effect.

**Comment by renpytom** [comment] 2021-09-19 20:02
No problem. I'm going to close this issue out.

**Closed by renpytom** 2021-09-19 20:02 UTC
