### ISSUE TITLE
[7.4.6] 'on' Statements not working for non-screen related transforms

### ISSUE THREAD

**Issue by solarProtag** [renpy/renpy#2873] opened 2021-06-27 20:04 UTC
As of the latest update, when I try to show any non-screen related objects or items — like images for example — with a transform that contains on statements such as "on show" or "on hide" it doesn't run those parts of the transform.

For example, I have this transform in my game that calls a small "mini CG" image to the center of the screen:

```
transform minipos:
    xalign 0.5
    yalign 0.4
    alpha 0.0
    yoffset 20
    on show:
        linear 0.3 alpha 1.0 yoffset 0
    on hide:
        linear 0.3 alpha 0.0 yoffset 20
```

Before this latest update it worked fine; used the on show portion when I showed it, then followed the on hide portion when I hid it. But now it's stuck at the part before the on blocks (I checked this by removing the alpha and it does indeed appear at the x and y aligns I've marked). 

This works fine for any screens that use on show/hide transforms but only images are facing this issue right now.
Thanks for reading!

**Comment by AndriWilford** [comment] 2021-07-05 15:02
I believe this is a duplicate of https://github.com/renpy/renpy/issues/2860

**Comment by solarProtag** [comment] 2021-07-05 18:15
> I believe this is a duplicate of #2860

I saw that a bit after I had posted my thread, but having to add that extra bit just for something that worked before the 7.4.6 update to work again is a little redundant imo.

**Comment by renpytom** [comment] 2021-07-10 22:23
I believe this is fixed in the nightlies.

**Closed by renpytom** 2021-07-10 22:23 UTC
