### ISSUE TITLE
[Idea] Warping to a Line from game console.

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3626] opened 2022-06-08 01:02 UTC
This could be very useful for traveling between the lines from within the game, I am aware of the existence of ["Warping to a Line"](https://www.renpy.org/doc/html/developer_tools.html#warping-to-a-line), However, it wouldn't hurt to have it inside the console that has renpy.

Ex:
![imagen](https://user-images.githubusercontent.com/36079551/172508973-de0d78b7-3cb1-41c7-8cb1-b4b417b60434.png)

Since you are inside the game, I don't think it is necessary to specify it .rpy

**Comment by renpytom** [comment] 2022-06-08 02:23
Honestly, warp doesn't work very well - I don't want to encourage its use, for that reason. The problem is that it doesn't set up data, that kind of thing.

**Comment by Neyunse** [comment] 2022-06-08 02:43
> Honestly, warp doesn't work very well - I don't want to encourage its use, for that reason. The problem is that it doesn't set up data, that kind of thing.

Maybe this can be looked at in some future, this would help a lot of moving forward when debugging the game, but it seems more complex than I thought. Or perhaps some other way to jump to a line of dialog that does not create problems.
Since using `jump` with a very long `label` can be a bit annoying to debug on a particular line.

**Comment by renpytom** [comment] 2022-07-28 01:17
This is fixed by 5ffbbc5531f841928b848c511dd2dacf970d7e8d , which adds the renpy.warp_to_line function.

**Closed by renpytom** 2022-07-28 01:17 UTC
