### ISSUE TITLE
IOS Port crash

### ISSUE THREAD

**Issue by am1guard** [renpy/renpy#4915] opened 2023-08-15 20:23 UTC
When I port some games to ios, after entering the game, it exits the game without giving an error. It happens in some games and not in others. I thought the reason was the python version, but I was wrong. How can I solve this problem?

**Comment by renpytom** [comment] 2023-08-17 02:25
Please run the game under Xcode, and look at the console for information that display the cause of the crash.

**Comment by renpytom** [comment] 2023-08-27 03:59
Closing as no new information has been provided.

**Closed** 2023-08-27 03:58 UTC
