### ISSUE TITLE
Tutorial project won't launch with Russian letters in it's full path

### ISSUE THREAD

**Issue by kxkw** [renpy/renpy#4759] opened 2023-06-20 15:04 UTC
Fresh install of RenPy 8.1.1, Windows 10

When trying to launch the Tutorial project it will show a brief loading screen, and nothing happens after that. No errors, no new windows. Full path is on the screenshot. 

![image](https://github.com/renpy/renpy/assets/130280061/bfd3f02b-9869-47f7-aa75-d8942ff34b64)

But, if i change the parent folder name from "Приложения" to "Apps", it will launch with no problems at all.

Here's full `log.txt` from the Tutorial project with Russian letters in it's full path after trying to launch:

```
Tue Jun 20 20:29:20 2023
Windows-10-10.0.19045
Ren'Py 8.1.1.23060707
 

Bootstrap to the start of init.init. took 0.02s
Early init. took 0.00s
Loader init. took 0.04s
Loading error handling. took 0.10s
Loading script. took 3.24s
Loading save slot metadata. took 0.05s
Loading persistent. took 0.00s
Running init code. took 0.40s
Loading analysis data. took 0.01s
Analyze and compile ATL. took 0.01s
Reloading save slot metadata. took 0.03s
Index archives took 0.00s
Dump and make backups. took 0.04s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.03s
DPI scale factor: 1.750000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.20s
Cleaning stores took 0.00s
Init translation took 0.05s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.06s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Performance test:
Interface start. took 0.08s

Initializing gl2 renderer:
primary display bounds: (0, 0, 3840, 2160)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 531.79'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(2240, 1260) drawable=(2240, 1260)
Maximum texture size: 4096x4096
```

**Comment by mal** [comment] 2023-06-20 16:11
Duplicate of https://github.com/renpy/renpy/issues/215, some work-arounds can be found [here](https://github.com/renpy/renpy/issues/215#issuecomment-1218051299).

**Comment by Gouvernathor** [comment] 2023-06-20 16:16
It is also warned about in the doc, [here](https://www.renpy.org/doc/html/problems.html#windows-encoding-problems).

**Comment by renpytom** [comment] 2023-07-03 02:21
I'm not able to repeat this on 8.1.1, with the system encoding set to Japanese, and a cyrillic directory name. Can anyone figure out how to repeat this on Ren'Py 8?

**Comment by mal** [comment] 2023-07-03 02:54
I can recreate this on a Windows 10 system where "Language for non-Unicode programs" is set to "English (United Kingdom)", using the path `...\Desktop\риложен\renpy-8.1.1-sdk\the_question`, where renpy-8.1.1-sdk is newly extracted. The SDK launches as expected from `renpy.exe`, but attempting to launch either The Question or the Tutorial results in `pythonw.exe` momentarily starting then ending (it comes and goes too quick to attempt any process inspection). Nothing additional is recorded in the SDK's `log.txt`, and no additional files are generated.

**Comment by mal** [comment] 2023-07-03 03:49
Using a console window, this works:
```
[...]\desktop\latin\renpy-8.1.1-sdk>lib\py3-windows-x86_64\python.exe
Python 3.9.10 (heads/mingw-v3.9.10-dirty:6407bc7c4a, Apr  1 2023, 23:45:07)  [GCC Clang 15.0.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

but this does not:
```
[...]\desktop\риложен\renpy-8.1.1-sdk>lib\py3-windows-x86_64\python.exe
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'lib\py3-windows-x86_64\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '[...]\\desktop\\\u0440\u0438\u043b\u043e\u0436\u0435\u043d\\renpy-8.1.1-sdk\\lib\\py3-windows-x86_64\\python.exe'
  sys.base_prefix = '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64'
  sys.base_exec_prefix = '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64'
  sys.platlibdir = 'lib'
  sys.executable = '[...]\\desktop\\\u0440\u0438\u043b\u043e\u0436\u0435\u043d\\renpy-8.1.1-sdk\\lib\\py3-windows-x86_64\\python.exe'
  sys.prefix = '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64'
  sys.exec_prefix = '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64'
  sys.path = [
    '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64\\lib\\python39.zip',
    '\\home\\tom\\ab\\renpy-build\\tmp\\install.windows-x86_64\\lib\\python3.9',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000039f8 (most recent call first):
<no Python frame>
```

**Closed** 2023-08-24 03:46 UTC
Labels: duplicate
