### ISSUE TITLE
LayeredImage with relative positions inside a screen renders wrong positions

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2071] opened 2019-12-10 03:32 UTC
https://lemmasoft.renai.us/forums/viewtopic.php?p=522200#p522200

**Comment by Gouvernathor** [comment] 2022-04-18 00:48
Test code :
```py
define photo_scale_factor = 1.
default neglectful = 25
image pond = Placeholder(base="bg", text="pond")
image him happy = Placeholder(base="boy", full=True)
image her normal = Placeholder(base="girl", full=True)
image kid happy = Placeholder(base="girl")
image kid sad = Placeholder(base="boy")
image polaroid = "#f002"

layeredimage family_photo:
    xysize (1000, 800)
    always:
        "pond"
    if (neglectful < 50):
        align(0.3, 1.0)
        "him happy"
    if True:
        align(0.7, 1.0)
        "her normal"
    group kid:
        align(0.45, 1.0)
        attribute happy:
            "kid happy"
        attribute sad:
            "kid sad"
    if True:
        "polaroid"

image family_photo_small = LayeredImageProxy("family_photo", Transform(crop=(306, 22, 675, 680), zoom=photo_scale_factor))

screen test_family_photo_screen():
    frame:
        xfill True
        yfill True
        hbox:
            vbox:
                label "Photo 1"
                add "family_photo_small happy"
            vbox:
                label "Photo 2"
                label "We'll move this down a little."
                add "family_photo_small happy"
            textbutton "Done" action Return()

label test2071:
    scene black
    show family_photo
    pause

    scene black
    show family_photo_small happy
    pause

    scene black
    call screen test_family_photo_screen
    return
```
The first part is a bunch of defines and default and images to test the thing properly without the variable environment nor the image sprites.
The second part is copy-pasted from the lemmasoft post, except the xysize which I added to roughly exceed the dimensions of the crop.
The last part is to try and reproduce what's described.

I can't reproduce what's described, aka the `show family_photo_small happy` having no offset, perfectly clean, and having an offset appearing on the screen.
There may be a problem with the crop, because removing 300 pixels from the left part of the image seems a lot, and very likely to cause an offset to the left as illustrated in the original post. However, even if that were (part of) the problem, it wouldn't explain how the right `add` in the screen gets offset but the left one doesn't.

**Comment by qirien** [comment] 2022-04-18 16:26
Yes, this looks fixed in the nightly build, thank you!

**Closed** 2022-04-19 02:51 UTC
