### ISSUE TITLE
Bug or not?

### ISSUE THREAD

**Issue by XelaPy** [renpy/renpy#1116] opened 2017-01-21 14:25 UTC
Under this setup, the second text displayable gets stuck on Cat when the script makes it to Cow. I am not 100% sure if it's a bug or expected behavior as it does not occur with window set on "auto"... as usual original code is very long but it all comes down to this:

```renpy
# options.rpy
define config.window = "hide"

# screens.rpy
screen say(who, what):
    style_prefix "say"

    if who is not None:
        vbox:
            text who
            fixed:
                at Transform(yzoom=.6)
                text who at Transform(alpha=.6) # Second text displayable
                
    # ... rest of the normal say screen...
    
# script.rpy
label start:
    "Cat" "Meow!"
    "Cow" "Mooo!"

**Comment by renpytom** [comment] 2017-01-23 16:37
I'm reopening this for a bit, so I can check it out more. While the issue is fixed by this, I think the real problem is displayables being copied when they don't need to be. So I'm going to leave this open to remind me of that problem.

**Comment by renpytom** [comment] 2017-02-01 03:26
I believe this has been closed completely now. If you can, please grab a nightly and let me know if Ren'Py is working.

**Comment by XelaPy** [comment] 2017-02-01 15:59
Yes, this was a problem in a whole bunch of places, all of those are now fixed. There is one more thing that might be related and doesn't update itself properly:

`screen vp_test():
    default mode = 1
    
    viewport:
        scrollbars "vertical"
        draggable True
        mousewheel True
        xysize 270, 302
        has vbox spacing 5
        
        if mode == 1:
            for i in xrange(100):
                add Solid("F00", ysize=20)
            
    vbox:
        align 1.0, .5
        textbutton "Mode 1":
            action SetScreenVariable("mode", 1)
        textbutton "Mode 2":
            action SetScreenVariable("mode", 2)
    
label start:
    call screen vp_test`

if you scroll down the viewport, lets say to the middle, and change to mode 2, content of the viewport will be updated (to nothing at all) _BUT_ the **scrollbar** displayable will remain unchanged.

**Thanks** again for looking into this issue, amount of broken screen shown displayable it has fixed for our new project is huge!

**Closed** 2017-02-06 06:46 UTC
