### ISSUE TITLE
renpy.py uses not widely supported shebang

### ISSUE THREAD

**Issue by jbeich** [renpy/renpy#869] opened 2016-03-09 00:16 UTC
Regressed by ecd36ec.
```
$ uname -sr
FreeBSD 11.0-CURRENT
$ ./renpy.py
env: python #@PydevCodeAnalysisIgnore: No such file or directory
```
http://www.in-ulm.de/~mascheck/various/shebang/#comments

**Comment by apoleon** [comment] 2016-03-14 11:40
I can confirm this issue. For the Debian distribution I had to remove #@PydevCodeAnalysisIgnore from renpy.py because renpy wouldn't start otherwise.

**Comment by renpytom** [comment] 2016-03-18 01:06
I've removed the shebang line entirely from the git repository and the versions of Ren'PY I distribute.

The thinking behind this is that, in general, one doesn't want to run downloaded Ren'Py games directly using the globally-installed python. One either wants to use <something>/bin/renpy to use the system install of Ren'Py, or ./renpy.sh, as desired. Mixing globally-installed modules with a newer game is unlikely to work.

Since this was unclear, I've removed the x-bit from renpy.py in git. It already was being removed when building distros.

I think it makes sense to add back the shebang when creating a distro package of Ren'Py. 

I'm closing this issue, but feel free to let me know if my reasoning is flawed.

**Comment by apoleon** [comment] 2016-03-18 12:37
Am 18.03.2016 um 02:06 schrieb Tom Rothamel:
> I've removed the shebang line entirely from the git repository and the
> versions of Ren'PY I distribute.
> 
> The thinking behind this is that, in general, one doesn't want to run
> downloaded Ren'Py games directly using the globally-installed python.
> One either wants to use /bin/renpy to use the system install of Ren'Py,
> or ./renpy.sh, as desired. Mixing globally-installed modules with a
> newer game is unlikely to work.
> 
> Since this was unclear, I've removed the x-bit from renpy.py in git. It
> already was being removed when building distros.
> 
> I think it makes sense to add back the shebang when creating a distro
> package of Ren'Py.
> 
> I'm closing this issue, but feel free to let me know if my reasoning is
> flawed.

Hi,

I think it wasn't necessary to remove the shebang completely. Just the
combination of

#!/usr/bin/env python

and

#@PydevCodeAnalysisIgnore

on the same line throws this runtime error.

The source release of Ren'Py doesn't include renpy.sh. That's why we
symlink from /usr/games/renpy to /usr/share/games/renpy/renpy.py to make
the renpy command globally available and that works fine.

It would be great if you could add the shebang #!/usr/bin/env python
back to renpy.py, so that we don't need to work around this by patching
renpy.py or creating our own renpy.sh start script.

**Comment by renpytom** [comment] 2016-03-19 00:01
Well, I kind of need #@PydevCodeAnalysisIgnore on the first line for my development environment to work - if I don't have it, it gets tons of errors. And I think for a non-distro Ren'Py, the shebang is actively misleading, as it implies that if only one chmods the file, things will work.

So, I kind of disagree - I think as part of the changes in going from a user to a distrol install, it actually does make sense to patch renpy.py or create a start script.

**Comment by apoleon** [comment] 2016-03-19 00:32
Am 19.03.2016 um 01:01 schrieb Tom Rothamel:
> Well, I kind of need #@PydevCodeAnalysisIgnore on the first line for my
> development environment to work - if I don't have it, it gets tons of
> errors. And I think for a non-distro Ren'Py, the shebang is actively
> misleading, as it implies that if only one chmods the file, things will
> work.
> 
> So, I kind of disagree - I think as part of the changes in going from a
> user to a distrol install, it actually does make sense to patch renpy.py
> or create a start script.

Yeah but your development environment and your release should be
actually two very different animals. As long as this change is only
included in Git, your development environment, there is no problem. But
you should avoid including this kind of shebang into a release because
it obviously makes renpy.py fail if it is executed in a Linux or FreeBSD
environment and apparently it worked before.

Patching renpy.py or creating a start script is additional work. As a
maintainer who packaged hundreds of other packages before, I would
expect that such a script is included in a release tarball. Additional
work is bad because people quickly lose interest if they constantly need
to patch software. So please there must be a better way.

**Comment by renpytom** [comment] 2016-03-19 01:06
I'll keep this open, for now. The problem is right now the Ren'Py distro scripts use the same files for the source and binary distros. I'd have to somehow split that.

**Closed** 2016-03-19 02:59 UTC

**Comment by renpytom** [comment] 2016-03-19 03:05
Okay, we'll now be adding:

#!/usr/bin/env python2

At the start of renpy.py in the source tarball only.
