### ISSUE TITLE
Renpy.exe uses 25% cpu (one whole core) abusively when it is supposed to sit idle.

### ISSUE THREAD

**Issue by jack4455667788** [renpy/renpy#1948] opened 2019-07-19 17:11 UTC
This bug was introduced around 7.2 / 7.3 and it is a showstopper.  I have confirmed it in the latest 7.3.2 as well.

Please fix your shitty code that is wasting processing cycles or I will have no choice but to use previous versions that don't have the bug.

Replicating the bug is as simple as opening renpy, starting up a renpy project (this may not be a necessary step) and leaving the renpy.exe launcher open.  After an indeterminate amount of time (seems to vary, but usually does not take long), it starts to wildly abuse the processor for no clear reason.

Please let me know if you need any more detail from me to help you debug this embarrassing infinite loop type situation. 

Win7 x64, quad core i7 machine, latest 7.3.2 sdk just downloaded today.

Thanks!

**Comment by renpytom** [comment] 2019-07-19 21:07
I've blocked the reporter of this bug.

@trajano, since you gave it a thumbs up, can you repeat this yourself?

**Comment by renpytom** [comment] 2019-07-19 23:37
Didn't recur when running for 2h here. Closing unless someone can reproduce the issue.

**Closed by renpytom** 2019-07-19 23:37 UTC

**Comment by trajano** [comment] 2019-07-19 23:44
@renpytom Yes I am getting some weird CPU spikes on my side but I can't consistently replicate it.  I just reboot when it happens.

**Comment by renpytom** [comment] 2019-07-19 23:44
Is it persistent, or does it just spike for a bit?

**Comment by StudioErrilhl** [comment] 2019-07-19 23:54
I've experienced this across most versions of Renpy since 6.9x at least, some CPU spiking, averaging maybe 12-15% usage. Haven't checked per core, as it's irrelevant to me.

It also happens more often than not if I have multiple projects open, or test heavy content in a project. Animations, continuous updates, multiple screens with active elements, etc. 

This is, however, not limited to Renpy, and I think it's more an issue with Python on Windows than anything else, as I've seen similar issues with other Pyhon based programs.

**Comment by trajano** [comment] 2019-07-20 00:00
Persistent but just one core as the reporter had noted, I have 6-cores (HT to 12) so it doesn't affect me as much.  Basically if I check it looks like this 

![image](https://user-images.githubusercontent.com/110627/61571096-1b691f80-aa5f-11e9-9e0e-ee1236d783d7.png)

There'd be one which is pegging the Core and it would say it's Pythonw when I hover.  Noting that it is pythonw rather than renpy.exe I am suspecting it may be something to do with the game rather than renpy itself.

@StudioErrilhl I wonder if you noticed it with just Python 32-bit or if 64-bit python reduces the occurrence.
