### ISSUE TITLE
Python 2.7.9 Error (assert --> try)

### ISSUE THREAD

**Issue by Xela00** [renpy/renpy#701] opened 2015-07-27 09:22 UTC
http://simpy.readthedocs.org/en/latest/

This took me over 20 hours to track down. The module works flawlessly when installed on real Python 2.7.9. It should do the same in Ren'Py as it has no dependencies Ren'Pys Python does not offer.

However this Error comes up in most tests:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 51, in script
    python:
  File "game/script.rpy", line 56, in <module>
    env.run()
RuntimeError: <Release() object at 0x4a5a4d0> has already been triggered

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 51, in script
    python:
  File "D:\Coding\Dropbox\Dev\RenPy\renpy\ast.py", line 797, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Coding\Dropbox\Dev\RenPy\renpy\python.py", line 1448, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 56, in <module>
    env.run()
  File "D:/Coding/Dropbox/Dev/RenPy/TestBed/game/simpy-3.0.8-py2.7.egg\simpy\core.py", line 137, in run
    self.step()
  File "D:/Coding/Dropbox/Dev/RenPy/TestBed/game/simpy-3.0.8-py2.7.egg\simpy\core.py", line 221, in step
    callback(event)
  File "D:/Coding/Dropbox/Dev/RenPy/TestBed/game/simpy-3.0.8-py2.7.egg\simpy\resources\base.py", line 241, in _trigger_get
    proceed = self._do_get(get_event)
  File "D:/Coding/Dropbox/Dev/RenPy/TestBed/game/simpy-3.0.8-py2.7.egg\simpy\resources\resource.py", line 179, in _do_get
    event.succeed()
  File "D:/Coding/Dropbox/Dev/RenPy/TestBed/game/simpy-3.0.8-py2.7.egg\simpy\events.py", line 131, in succeed
    raise RuntimeError('%s has already been triggered' % self)
RuntimeError: <Release() object at 0x4a5a4d0> has already been triggered

Windows-8-6.2.9200
Ren'Py 6.99.6.611
TestBed 0.0

====================================
I've traced it down to:
simpy.resources.base.BaseResource._trigger_put

and

simpy.resources.base.BaseResource._trigger_get

Both have very similar lines:

        while idx < len(self.get_queue):
            get_event = self.get_queue[idx]
            proceed = self._do_get(get_event)
            if get_event.triggered:
                assert self.put_queue.pop(idx) == put_event

Error disappears and everything works normally if these are changed to:

        while idx < len(self.get_queue):
            get_event = self.get_queue[idx]
            proceed = self._do_get(get_event)
            if get_event.triggered:
                try:
                    self.get_queue.pop(idx) == get_event
                except:
                    pass

=====================
In this case it is no longer an issue but even if this cannot be fixed easily, at the very least it should be noted somewhere in documentation that such a thing may occur so people would know what to look for.

I replicated it on two computers, moving code to init python did not help either, just started to throw different errors. Problem is not with BoundClass class, I got rid of those then testing. It could be the insane traceback implementation or Ren'Pys parser... otherwise I do not have a clue on why this is happening.

**Comment by renpytom** [comment] 2015-07-27 12:59
The problem is that Ren'Py runs with Python's optimization enabled, which means that assert statements aren't run. The problem here is that means that self.get_queue.pop(idx) is not run, which means the event is not removed from the queue, giving you the problem that you're seeing.

You'll likely see the same problem with simpy if you run it with python -OO mycode.py.

I don't believe this a problem with Ren'Py, and hence, I'l closing this bug.

**Closed by renpytom** 2015-07-27 12:59 UTC

**Comment by Xela00** [comment] 2015-07-27 14:45
Thanks for the clarification :+1:
