### ISSUE TITLE
Game freezes when restoring window position from secondary monitors

### ISSUE THREAD

**Issue by juniorthejunior** [renpy/renpy#5325] opened 2024-01-30 14:01 UTC
Encountering an issue in Ren'Py 8.2.0 where, if I launch a game from the Launcher, move the game's window to a secondary monitor, and close the game there, on the next launch the game freezes on a fully white screen and becomes non-responsive until it is needed to be forcefully killed. This does not happen if the window was only moved elsewhere on the Primary monitor - that works as intended and the previous position gets restored.

The Primary monitor is a 21:9 2560x1080p, and the secondary monitors are a 16:9 4K (3840x2160px) one and a 16:10 1920x1200px; this happens when I move the game's window to either of them.

I was initially wondering if this was due to the varying resolutions of the monitors, but that did not seem to be the case: I asked a few people with multi-monitor setups to test it out, one whose both monitors had the same resolution, and two others with also varying resolutions ((1920x1080px + 1920x1080px + 4K), and (2560x1080p+ 1920x1080px)); and they did _not_ experience this issue.

I also ran some experiments with making each monitor the Primary:
- If the 16:10 one is the Primary, the results are the same; moving the window to the other monitors makes it freeze on the next launch.
- If the 4K one is the Primary, moving the window to other monitors has no special result: it always gets reset back to the center of the 4K one, with no freezes or anything. It does also restore the position if it was set elsewhere on the 4K monitor itself.

I also tried changing the resolutions of all 3 monitors to 1920x1080px via Windows settings, that did not make a difference. 
Also tried unplugging each one of the monitors entirely, and the results were the same with the remaining monitors in all combinations.

Unsure of what else to test, but I tried printing out `preferences.window_position` and `preferences.window_position_layout` during Init to maybe help provide some clue:
```py
# Moved from Primary 21:9 to elsewhere on Primary 21:9:
renpy.game.preferences.window_position == (649, 31)
renpy.game.preferences.window_position_layout == ((0, 0, 2560, 1080), (-3840, -465, 2560, 1440), (2560, 2, 1920, 1200))

# Moved from Primary 21:9 to secondary 16:9 4K (freeze):
renpy.game.preferences.window_position == (-3560, -265)
renpy.game.preferences.window_position_layout == ((0, 0, 2560, 1080), (-3840, -465, 2560, 1440), (2560, 2, 1920, 1200))

# Moved from Primary 21:9 to secondary 16:10 1920x1200px (freeze):
renpy.game.preferences.window_position == (2633, 74)
renpy.game.preferences.window_position_layout == ((0, 0, 2560, 1080), (-3840, -465, 2560, 1440), (2560, 2, 1920, 1200))
```
Log file: [log.txt](https://github.com/renpy/renpy/files/14090267/log.txt)

This is on Ren'Py 8.2.0,
NVIDIA driver version: 551.23 (latest at this time)
OS:
    Edition: Windows 10 Pro
    Version: 22H2
    OS build: 19045.3930
    Experience: Windows Feature Experience Pack 1000.19053.1000.0

![Screenshot 2024-01-29_](https://github.com/renpy/renpy/assets/144063178/78a14186-042f-4e60-a558-7d6f742be23a)
![Screenshot 2024-01-29__](https://github.com/renpy/renpy/assets/144063178/e41bc6ba-f076-4599-ae05-53d90b19c024)

**Comment by juniorthejunior** [comment] 2024-01-30 14:34
Update: Changing the renderer to ANGLE2 fixes the issue.

**Comment by renpytom** [comment] 2024-01-30 15:50
I don't know what the problem is, but this is very unlikely to be a Ren'Py problem. Other than positioning the window where you last place it, Ren'Py is working the same way regardless of monitor. I'd suggest reporting this issue to Nvidia to see if they can help as all.

**Comment by danac78** [comment] 2024-01-30 23:17
@juniorthejunior Have you tried completely uninstalling the Nvidia Drivers, downloading the latest from Nvidia, restarting Windows, and Reinstalling the Drivers? Going into Device Manager, right-click on the video card(s), click on uninstall, and click the checkbox that Asks if you want to Delete Drivers. It will probably be something Nvidia will ask to see if it is a problem with their drivers, or if it is a problem with your currently installed drivers.

One thing about "updating drivers", it may not ALWAYS put the newest version of everything. There could be a lingering issue that could cause odd behaviors.

Additionally, they also may ask you if this happens in another profile (Username). Corrupted (or starting to corrupt) profiles can cause wide range of weird issues. It will help both them and you determine if it is system-wide or just account-wide.

Just two things to check that I did not see in your lists because I do not know how quick Nvidia is with responding to support requests.

**Comment by juniorthejunior** [comment] 2024-01-31 14:24
> @juniorthejunior Have you tried completely uninstalling the Nvidia Drivers, downloading the latest from Nvidia, restarting Windows, and Reinstalling the Drivers? Going into Device Manager, right-click on the video card(s), click on uninstall, and click the checkbox that Asks if you want to Delete Drivers. It will probably be something Nvidia will ask to see if it is a problem with their drivers, or if it is a problem with your currently installed drivers.
> 
> One thing about "updating drivers", it may not ALWAYS put the newest version of everything. There could be a lingering issue that could cause odd behaviors.
> 
> Additionally, they also may ask you if this happens in another profile (Username). Corrupted (or starting to corrupt) profiles can cause wide range of weird issues. It will help both them and you determine if it is system-wide or just account-wide.
> 
> Just two things to check that I did not see in your lists because I do not know how quick Nvidia is with responding to support requests.

Thanks for the suggestions. Followed the steps - deleted via Device Manager, restarted, installed 551.23 (the latest), restarted - and the problem still persists. I also repeated the process except uninstalling the driver using DDU (a third-party "deep uninstaller" of sorts), and that made no difference either.

Also made a new Windows account/profile, downloaded and ran Ren'Py 8.2.0 and the results were the same there as well.

I'll have to put together a report to NVIDIA at some point in the future, though at least for the time being, I am disabling this feature entirely in my project, since I personally would not want a player to encounter it and have them have to deal with it (however rare it might be; if it's happened to me, it'll happen to someone else), especially for a mostly QoL feature.

**Comment by lauwurence** [comment] 2024-02-22 10:33
I have almost the same issue. Found that it was Discord that was messing something up sometimes and that was causing the videos on YouTube to not play and Ren'Py games freezing on closing.

**Comment by renpytom** [comment] 2024-02-25 01:47
I'm closing this, as it's likely to be some other process that's causing this problem.

**Closed by renpytom** 2024-02-25 01:47 UTC
