### ISSUE TITLE
RenPy crashing on reload (Launcher and any project)

### ISSUE THREAD

**Issue by Tooi** [renpy/renpy#4693] opened 2023-06-04 14:11 UTC
Hi there, my RenPy crashes every time I try to change the skin in the launcher or reload a project with Shift + R while playtesting (even creating a new one and trying it) and I have no idea why. It will sometimes flicker for a second, then completely close itself. In the case of the launcher, it shows a loading wheel after selecting a skin and then closes.

I don't get a traceback file, but it does generate a log file which I have put below:

>Sun Jun  4 14:58:18 2023
>Windows-10-10.0.22621
>Ren'Py 8.1.0.23051307
> 
>
>Bootstrap to the start of init.init. took 0.02s
>Early init. took 0.01s
>Loader init. took 0.06s
>Loading error handling. took 0.03s
>Loading script. took 0.13s
>Loading save slot metadata. took 0.02s
>Loading persistent. took 0.00s
>Running init code. took 0.05s
>Loading analysis data. took 0.01s
>Analyze and compile ATL. took 0.00s
>Reloading save slot metadata. took 0.02s
>Index archives took 0.00s
>Dump and make backups. took 0.06s
>Cleaning cache. took 0.00s
>Making clean stores. took 0.00s
>Initial gc. took 0.01s
>DPI scale factor: 1.000000
>nvdrs: Loaded, about to disable thread optimizations.
>nvdrs: Disabled thread optimizations.
>Creating interface object. took 0.23s
>Cleaning stores took 0.00s
>Init translation took 0.02s
>Build styles took 0.00s
>Load screen analysis took 0.02s
>Analyze screens took 0.00s
>Save screen analysis took 0.00s
>Prepare screens took 0.04s
>Save pyanalysis. took 0.00s
>Save bytecode. took 0.00s
>Running _start took 0.00s
>Performance test:
>Interface start. took 0.11s
>
>Initializing gl2 renderer:
>primary display bounds: (0, 0, 2560, 1440)
>swap interval: 1 frames
>Windowed mode.
>Vendor: "b'NVIDIA Corporation'"
>Renderer: b'NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2'
>Version: b'4.6.0 NVIDIA 535.98'
>Display Info: None
>Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
>Could not open 'cache/shaders.txt':
>Maximum texture size: 4096x4096
>controller: '030000006d0400000000000000007200' '(Razer Xbox 360 Controller)' 1
>Controller found in blocklist, not using.
>controller: '030000006d0400000000000000007200' '(Razer Xbox 360 Controller)' 1
>Controller found in blocklist, not using.
>Resetting cache.
>Bootstrap to the start of init.init. took 3.72s
>Early init. took 0.00s
>Loader init. took 0.06s
>Loading error handling. took 0.03s
>Loading script. took 0.13s
>Loading save slot metadata. took 0.02s
>Loading persistent. took 0.00s
>Running init code. took 0.03s
>Loading analysis data. took 0.01s
>Analyze and compile ATL. took 0.00s
>Reloading save slot metadata. took 0.02s
>Index archives took 0.00s
>Dump and make backups. took 0.06s
>Cleaning cache. took 0.00s
>Making clean stores. took 0.00s
>Initial gc. took 0.02s
>DPI scale factor: 1.000000
>nvdrs: Loaded, about to disable thread optimizations.
>nvdrs: Disabled thread optimizations.
>Creating interface object. took 0.22s
>Cleaning stores took 0.00s
>Init translation took 0.02s
>Build styles took 0.00s
>Load screen analysis took 0.02s
>Analyze screens took 0.00s
>Save screen analysis took 0.00s
>Prepare screens took 0.04s
>Save pyanalysis. took 0.00s
>Save bytecode. took 0.00s
>Running _start took 0.00s
>Performance test:
>Interface start. took 0.29s
>
>Initializing gl2 renderer:
>primary display bounds: (0, 0, 2560, 1440)
>swap interval: 1 frames
>Windowed mode.
>Vendor: "b'NVIDIA Corporation'"
>Renderer: b'NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2'
>Version: b'4.6.0 NVIDIA 535.98'
>Display Info: None
>Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
>Maximum texture size: 4096x4096
>controller: '030000006d0400000000000000007200' '(Razer Xbox 360 Controller)' 1
>Controller found in blocklist, not using. 

I have tried a bunch of things including reinstalling RenPy, updating RenPy and even going to an older version but the same thing happens every time. If you require any more information or for me to do any more testing, let me know!

**Comment by renpytom** [comment] 2023-06-04 14:43
I'm not seeing any obvious reason here. Do you have any additonal information, from the windows debugging or anything like that? Please make sure you remove any "game enhancement" software that could change how Windows works.

**Comment by Tooi** [comment] 2023-06-04 15:20
Thank you for the reply, I don't have any kind of enhancement software but strangely enough after playing around with some settings on my PC, it seems that changing the Refresh Rate HZ of my second monitor (the one that I use for web browsing and media) from 60Hz to 160HZ, it seems to have resolved the issue for now?

I'm not really sure why that would be the case of if it was resolved by something else, but I will continue to test it and do some PC restarts to see if it sticks.

**Comment by renpytom** [comment] 2023-06-13 02:54
Closing the issue, as this doesn't seem to be something that is obviously caused by Ren'Py. Feel free to re-open this if  there's a more direct connection.

**Closed by renpytom** 2023-06-13 02:54 UTC
Labels: crash or exception

**Comment by t3h4nt1chr15t** [comment] 2024-12-17 21:34
I've just encountered nearly this exact issue, minus the refresh rate 'solution.' This is the only place I could find on the internet reporting a similar issue to mine, but I have some additional extra details to expand on what the OP might have been encountering...

I've traced the "Razer Xbox 360 controller" --> "Controller found in blocklist, not using" exit of the log to my Razer Huntsman V3 Pro. I think, because the keyboard has an analog setting for keys, which knows how far the key is pressed down, this is somehow being confused by the computer as an analogue controller, like an Xbox 360 controller, despite this not actually being a 360 controller. 

The reason I know that the cause of the issue is specifically the keyboard is because I've been able to replicate the problem reliably and disconnecting the keyboard, then launching the RenPy app/game, allows the game to launch with no issues whatsoever. Then you can plug the keyboard back in and play the game normally. However, close that game and try to immediately restart it without unplugging the keyboard, and it will go right back to crashing before it can fully launch, every single time, giving the same resulting log file:
-------------------------------------------
Tue Dec 17 00:51:57 2024
Windows-10-10.0.19045
Ren'Py 8.1.0.23051307
 

Bootstrap to the start of init.init. took 0.03s
Early init. took 0.00s
Loader init. took 0.14s
Loading error handling. took 0.47s
Loading script. took 4.00s
Loading save slot metadata. took 0.80s
Loading persistent. took 0.04s
Set script version to: (8, 1, 0)
Running init code. took 1.36s
Loading analysis data. took 0.10s
Analyze and compile ATL. took 0.44s
Reloading save slot metadata. took 0.46s
Index archives took 0.01s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.43s
DPI scale factor: 2.500000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.33s
Cleaning stores took 0.00s
Init translation took 0.43s
Build styles took 0.01s
Load screen analysis took 0.09s
Analyze screens took 0.01s
Save screen analysis took 0.00s
Prepare screens took 0.17s
Save pyanalysis. took 0.01s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.61s

Initializing gl2 renderer:
primary display bounds: (0, 0, 3840, 2160)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3090/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 566.36'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(3840, 2028) drawable=(3840, 2028)
Maximum texture size: 4096x4096
controller: '030000006d0400000000000000007200' '(Razer Xbox 360 Controller)' 1
Controller found in blocklist, not using.
----------------------------------------

So while the problem may not be sourced to RenPy itself, it's very clear that RenPy is what is 'opting' to not launch due to the controller being either banned, or as it says 'blocked.' What I don't know is if it's blocked because RenPy can't identify what it is, so it plays things safe, or if the controller (the keyboard) is legitimately on some sort of blocklist.

So I think this should actually be considered an issue with RenPy because all that seemingly needs to be done is for this controller, and likely any other keyboard that has analogue options, to be allowed for by Ren'Py. Or, if it's just RenPy playing things safe, to add some sort of condition for these types of keyboards for it to understand that these are actually perfectly safe to boot up the game under. Otherwise we will have to continue unplugging our keyboards just to start the darn games.
