### ISSUE TITLE
[7.4.5] Android game crashing on startup

### ISSUE THREAD

**Issue by pineapple2828** [renpy/renpy#2845] opened 2021-06-02 22:39 UTC
Samsung S8 using Android 9. 

Ren'py successfully builds the game's package, but upon testing on phone, the game crashes after the splashscreen. Previous versions of the game built with 7.4.3 before the bintray shutdown work.

Logcat error log when booting up a test game:

`2021-06-02 19:13:23.284 3938-4112/? E/InputDispatcher: channel 'c0c0e6c com.moritest/org.renpy.android.PythonSDLActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-06-02 19:13:23.417 3938-13124/? E/ActivityManager: Failed to schedule configuration change
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:1897)
        at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:129)
        at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
        at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:100)
        at com.android.server.am.ActivityManagerService.updateGlobalConfigurationLocked(ActivityManagerService.java:27400)
        at com.android.server.am.ActivityManagerService.updateDisplayOverrideConfigurationLocked(ActivityManagerService.java:27517)
        at com.android.server.am.ActivityManagerService.updateDisplayOverrideConfigurationLocked(ActivityManagerService.java:27494)
        at com.android.server.am.ActivityStackSupervisor.ensureVisibilityAndConfig(ActivityStackSupervisor.java:1983)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:3143)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2760)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2705)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2677)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:2627)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:2602)
        at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:7627)
        at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:7853)
        at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:2225)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:1211)
2021-06-02 19:13:23.464 3938-3964/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{c0c0e6c u0 com.moritest/org.renpy.android.PythonSDLActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3951)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5507)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)`

edit: can't seem to format the code properly, sorry

**Comment by renpytom** [comment] 2021-06-02 23:41
Can you post a longer logcat, please? I don't see the cause for the crash here.

**Comment by renpytom** [comment] 2021-06-02 23:44
Also, can you try a build with:

```
define config.gl2 = False
```

?

**Comment by pineapple2828** [comment] 2021-06-03 00:59
> 
> 
> Can you post a longer logcat, please? I don't see the cause for the crash here.

[logcat.txt](https://github.com/renpy/renpy/files/6588174/logcat.txt)

> 
> 
> Also, can you try a build with:
> 
> ```
> define config.gl2 = False
> ```
> 
> ?

Tried it just now, same result.

**Comment by renpytom** [comment] 2021-06-03 01:02
I need more than that - as of the last message:

06-02 21:17:05.631 29539 29573 I python  : Loading error handling took 0.10s

Ren'Py was still running.

**Comment by pineapple2828** [comment] 2021-06-03 01:59
Sorry, I was having some trouble sending the complete logcat here.

[logcat.txt](https://github.com/renpy/renpy/files/6588362/logcat.txt)

Actually, I noticed something weird there: python sems to be saying that there was an error loading the scriptch2.rpy file, but the file is there and the error doesn't happen when playing the game on the PC.

**Comment by renpytom** [comment] 2021-06-03 02:03
Ah, this is your problem. It's not actually there on Android. Android builds blacklist the .rpy files, so they shouldn't be included with Ren'Py, as they're not acessible on android. 

It's possible that rapt/blocklist.txt got updated. (It was renamed recently.), and you had the line that blocked .rpy files removed in previous versions.

**Comment by pineapple2828** [comment] 2021-06-03 13:04
Aaa, I edited the blocklist and it worked! Game's launching and playing just fine now.

Thank you so much and sorry for the trouble, Tom.

**Comment by renpytom** [comment] 2021-06-03 19:33
Glad we got it working. Closing this.

**Closed by renpytom** 2021-06-03 19:33 UTC
